feature: 新增 人员分组选择器变量(3.5.X_dev)
Tencent/bk-sops pull request #2530
Opened 2020-08-21 03:46 UTC by feifeizhao4754

- 新功能
    - 新增 人员分组选择器变量

2020-08-24 01:37 UTC, feifeizhao4754 commented on gcloud/core/models.py
> +    def staff_name_of_project(self):
没用到，这里会删除掉

2020-08-26 07:57 UTC, feifeizhao4754 commented on pipeline_plugins/variables/static/variables/staff_group_multi_selector.js
> +                        {text: gettext("运维人员"), value: "Maintainers"},
这里在`get_notify_receivers `函数中有相关映射

2020-08-27 03:33 UTC, homholueng approved these changes

2020-08-27 03:33 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/bk/notify/legacy.py
> +        res = get_notify_receivers(client,
需要确认下，legacy 前端表单传过来的角色列表是 cc1.0 版的代号还是 cc3.0 的代号，如果是 1.0 的，需要在调用 `get_notify_receivers` 之前使用 `CC_V2_ROLE_MAP` 转换下

2020-08-27 03:33 UTC, homholueng commented on gcloud/utils/cmdb.py
> +        receivers.extend(biz_data[CC_V2_ROLE_MAP[group]].split(","))
这里让用户直接传入 cc3.0 的角色代号，不需要再用 `CC_V2_ROLE_MAP` 来转换

2020-08-27 03:34 UTC, homholueng reviewed
Rquest changes

2020-08-28 08:35 UTC, homholueng requested changes

2020-08-28 08:35 UTC, homholueng commented on pipeline_plugins/components/static/components/atoms/bk/notify/legacy.js
> -                                {name: gettext("测试人员"), value: "Tester"},
已经在代码中转换了，这里就不要修改了

2020-08-28 08:35 UTC, homholueng commented on pipeline_plugins/components/static/components/atoms/bk/notify/v1_0.js
> -                                {name: gettext("运维人员"), value: "Maintainers"},
已经在代码中转换了，这里就不要修改了

2020-08-28 08:35 UTC, homholueng commented on static/components/atoms/bk/notify/legacy.js
> -                                {name: gettext("运维人员"), value: "Maintainers"},
已经在代码中转换了，这里就不要修改了

2020-08-28 08:35 UTC, homholueng commented on static/components/atoms/bk/notify/v1_0.js
> +                                {name: gettext("运维人员"), value: "bk_biz_maintainer"},
已经在代码中转换了，这里就不要修改了

2020-08-31 06:47 UTC, homholueng approved these changes

2020-08-31 06:48 UTC, merged