feature: 模板编辑、任务执行画布页面任务节点增加插件生命周期标记(V3.6.X_dev)
Tencent/bk-sops pull request #2578
Opened 2020-08-27 11:22 UTC by fannluo

- 新功能
    - 模板编辑、任务执行画布页面任务节点增加插件生命周期标记

2020-08-28 02:14 UTC, homholueng requested changes

2020-08-28 02:14 UTC, homholueng commented on frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
> +                    '1': i18n.t('当前插件已停止维护，即将下线，请更新插件'),
当前插件即将停止维护，请更新插件版本

2020-08-28 02:14 UTC, homholueng commented on frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/TaskNode.vue
> +                    '2': i18n.t('当前插件已停止维护，请更新插件')
当前插件已停止维护，请更新插件版本

2020-08-31 11:47 UTC, v-xugzhou approved these changes

2020-08-31 12:17 UTC, homholueng approved these changes

2020-08-31 12:17 UTC, merged