improve: 返回值为对象类型的变量直接引用场景下的结果优化
Tencent/bk-sops pull request #2747
Opened 2020-09-16 08:21 UTC by normal-wls

- 优化项
    - 返回值为对象类型的变量直接引用场景下的结果优化

2020-09-23 08:55 UTC, homholueng requested changes

2020-09-23 08:55 UTC, homholueng commented on pipeline/core/data/expression.py
> +            if hasattr(value_obj, "default_value"):
这里不建议用 `default_value` 作为属性值，冲突概率有些大，可以改成 `_pipeline_var_str_value`

2020-09-23 08:55 UTC, homholueng commented on pipeline/core/data/expression.py
> -        # TODO keep render return object, here only process simple situation
pipeline 改动需要同步到 git.code

2020-09-27 07:43 UTC, normal-wls commented on pipeline/core/data/expression.py
> -        # TODO keep render return object, here only process simple situation
后续会进行同步

2020-09-27 08:08 UTC, homholueng approved these changes

2020-09-27 08:08 UTC, merged