feature：完成插件 CMDB-按规则修改主机属性
Tencent/bk-sops pull request #2753
Opened 2020-09-17 03:36 UTC by Atropos1999

2020-09-23 08:50 UTC, homholueng requested changes

2020-09-23 08:50 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
> +        if not ip_list["result"] or not ip_list["ip_count"]:
如果返回结果中存在 `invalid_ip` 也需要报错，并提示用户哪些 ip 是非法的

2020-09-23 08:50 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
> +        set_kwargs = {"bk_biz_id": biz_cc_id, "bk_ids": set_id_list, "fields": set_rule_list}
这里可以优化一下，如果用户没有选择集群规则就不请求 cmdb 接口

2020-09-23 08:50 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
> +        module_kwargs = {"bk_biz_id": biz_cc_id, "bk_ids": module_id_list, "fields": module_rule_list}
同上

2020-09-24 12:21 UTC, homholueng approved these changes

2020-09-24 12:21 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/cc/host_custom_property_change/v1_0.py
> +            data.outputs.ex_data = _("无法从配置平台(CMDB)查询到对应 IP，请确认输入的 IP 是否合法")
invalid_ip 中的 ip 要展示出来

2020-09-24 12:21 UTC, homholueng requested changes
see discussions

2020-09-27 07:12 UTC, homholueng approved these changes

2020-09-28 08:07 UTC, normal-wls approved these changes

2020-09-28 09:39 UTC, merged