feature: 完成全局变量 集群分组选择器（3.6.X）
Tencent/bk-sops pull request #2764
Opened 2020-09-18 02:02 UTC by Atropos1999

2020-09-18 02:02 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/bk-sops?pullRequest=2764) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-sops?pullRequest=2764) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-sops?pullRequest=2764) it.</sub>

2020-09-23 08:06 UTC, homholueng requested changes

2020-09-23 08:06 UTC, homholueng commented on pipeline_plugins/variables/collections/sites/open/docs/cmdb/var_set_group_selector.md
> +	"bk_enable_relate_webplat": [],
这里返回格式的示意按照外部版的来写

2020-09-23 08:06 UTC, homholueng commented on pipeline_plugins/variables/collections/sites/open/docs/cmdb/var_set_group_selector.md
> +* `flat__set_name` 字符串格式的集群ID
分隔符要说明

2020-09-23 08:06 UTC, homholueng commented on pipeline_plugins/variables/collections/sites/open/cmdb/var_set_group_selector.py
> +set_field = [
这里也不能写死，需要拉取 cmdb 当前业务下集群模型有哪些属性，再请求这些属性

2020-09-24 10:04 UTC, homholueng requested changes

2020-09-24 10:04 UTC, homholueng commented on pipeline_plugins/variables/collections/sites/open/cmdb/var_set_group_selector.py
> +        set_field = get_set_property(operator)
cc_execute_dynamic_group 调用过一次 get_set_property，这里又调用了一次，可以在 cc_execute_dynamic_group 之前执行一次 get_set_property 获取集群属性就好了吧

2020-09-24 11:19 UTC, homholueng approved these changes

2020-09-24 11:19 UTC, merged