feature:CMDB-批量修改集群属性（支持进行单行扩展）
Tencent/bk-sops pull request #2885
Opened 2020-10-22 06:48 UTC by 352671669

- 新功能
feature:CMDB-批量修改集群属性（支持进行单行扩展）

2020-10-26 06:41 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +VERSION = "v1.0"
1.0 即可

2020-10-26 06:41 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +        )
这里写得太冗余了
```
data.get_one_of_inputs("cc_set_template_break_line") or ","
```

2020-10-26 06:41 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +            search_result = client.cc.search_set(kwargs)
search_set 是强制要求分页的，将 search_set 操作封装到 batch_request 中

2020-10-26 06:41 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +        return []
缺少 set_update_failed 和 set_update_success 的定义

2020-10-26 06:41 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +        return False
写 ex_data

2020-10-26 06:41 UTC, homholueng commented on pipeline_plugins/components/static/components/atoms/cc/batch_update_set/v1_0.js
> +                                "name": "目前Set名称",
`Set名称`即可

2020-10-26 06:41 UTC, homholueng commented on pipeline_plugins/components/static/components/atoms/cc/batch_update_set/v1_0.js
> +/**
static 目录下也要添加该文件

2020-10-26 06:41 UTC, homholueng requested changes
see conversation

2020-10-26 07:13 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +VERSION = "v1.0"
已修改

2020-10-26 07:14 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +        )
已修改

2020-10-26 07:16 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +            search_result = client.cc.search_set(kwargs)
已修改

2020-10-26 07:19 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +        return False
已修改

2020-10-26 07:26 UTC, 352671669 commented on pipeline_plugins/components/static/components/atoms/cc/batch_update_set/v1_0.js
> +                                "name": "目前Set名称",
已修改

2020-10-26 07:26 UTC, 352671669 commented on pipeline_plugins/components/static/components/atoms/cc/batch_update_set/v1_0.js
> +/**
已添加

2020-10-26 07:29 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +        return []
已添加

2020-10-28 08:40 UTC, homholueng requested changes

2020-10-28 12:01 UTC, closed without merging