feature:CMDB-批量修改集群属性（支持进行单行扩展）
Tencent/bk-sops pull request #2920
Opened 2020-10-28 12:02 UTC by 352671669

- 新功能
    - feature:CMDB-批量修改集群属性（支持进行单行扩展）

2020-10-28 13:52 UTC, homholueng requested changes

2020-10-28 13:52 UTC, homholueng commented on pipeline_plugins/components/query/sites/open/cc.py
> +            )
attrs 的组装在前端做，后台逻辑返回属性 id 和属性名即可

2020-10-28 13:52 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +VERSION = "v1.0"
1.0 即可

2020-10-28 13:52 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +        return False
更新失败的集群应该写到一个 outputs 字段中

2020-10-29 02:23 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +VERSION = "v1.0"
已修改

2020-10-29 02:32 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/cc/batch_update_set/v1_0.py
> +        return False
已修改

2020-10-29 03:44 UTC, closed without merging