improve: 新增 api 分页装饰器 并 支持 get_task_list 接口
Tencent/bk-sops pull request #2956
Opened 2020-11-06 06:41 UTC by normal-wls

- 优化项
    - 新增 api 分页装饰器 并 支持 get_task_list 接口

2020-11-12 09:00 UTC, homholueng requested changes

2020-11-12 09:00 UTC, homholueng commented on gcloud/apigw/decorators.py
> +            if limit == 0 and offset == 0:
在响应返回的地方处理分页不太合适，分页主要是为了缓解全量拉取 DB 带来的压力

2020-11-16 08:46 UTC, normal-wls commented on gcloud/apigw/decorators.py
> +            )
已去掉

2020-11-16 08:46 UTC, normal-wls commented on gcloud/apigw/decorators.py
> +            if limit == 0 and offset == 0:
实现改成工具函数

2020-11-30 09:02 UTC, homholueng approved these changes

2020-11-30 09:02 UTC, merged