feature: 任务启动操作添加基于业务的次数限制及对应设置选项
Tencent/bk-sops pull request #2992
Opened 2020-11-16 03:43 UTC by normal-wls

- 新功能
    - 任务启动操作添加基于业务的次数限制及对应设置选项

2020-11-30 08:46 UTC, homholueng requested changes

2020-11-30 08:46 UTC, homholueng commented on config/default.py
> +TASK_OPERATION_THROTTLE = os.getenv("TASK_OPERATION_THROTTLE", True)
环境变量前添加 BKAPP，不然 V2 版本的 PAAS 配置不了这个环境变量

2020-11-30 08:46 UTC, homholueng commented on gcloud/utils/throttle.py
> +def check_task_operation_throttle(project_id, operation):
需要单元测试

2020-11-30 08:46 UTC, homholueng commented on gcloud/utils/throttle.py
> +    cache.set(token_num_key, token_num)
多个线程并发访问这个函数的时候会有问题吧

2020-12-30 07:37 UTC, homholueng requested changes

2020-12-30 07:37 UTC, homholueng commented on config/default.py
> +TASK_OPERATION_THROTTLE = os.getenv("BKAPP_TASK_OPERATION_THROTTLE", True)
环境变量整合到 env

2020-12-30 07:37 UTC, homholueng commented on gcloud/utils/throttle.py
> +task_operation_throttle_lock = Lock()
线程锁在协程模式下是否能生效？

2021-01-17 06:37 UTC, normal-wls commented on gcloud/utils/throttle.py
> +    cache.set(token_num_key, token_num)
> 多个线程并发访问这个函数的时候会有问题吧

已添加单元测试验证

2021-03-18 13:23 UTC, homholueng approved these changes

2021-03-18 13:24 UTC, homholueng commented on gcloud/utils/throttle.py
> +    try:
考虑使用 redis？

2021-05-17 03:02 UTC, homholueng approved these changes

2021-05-19 11:27 UTC, merged