bugfix:"IP存在性校验"在存在多个相同 IP 时会不通过
Tencent/bk-sops pull request #3075
Opened 2020-12-07 08:20 UTC by 352671669

- bug fix
    -"IP存在性校验"在存在多个相同 IP 时会不通过

2020-12-11 12:00 UTC, homholueng requested changes

2020-12-11 12:00 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
> +                    input_ip_list = list(set(get_ip_by_regex(val)))
这里直接 set 就不用再转 list 了，后续需要使用到 set 的地方也不需要再转了

2020-12-11 12:00 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
> -                    input_ip_list = get_ip_by_regex(val)
补充 dev_log

2020-12-30 07:56 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
> -                    input_ip_list = get_ip_by_regex(val)
已补充

2020-12-30 07:56 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
> +                    input_ip_list = list(set(get_ip_by_regex(val)))
已修改

2021-01-12 07:23 UTC, homholueng commented on dev_log/dev/spacesun202012301550.yaml
> +  - "IP存在性校验"在存在多个相同 IP 时会不通过
dev log 完善：修复"IP存在性校验"在存在多个相同 IP 时会不通过的问题

2021-01-12 07:23 UTC, homholueng requested changes
see discussion

2021-01-12 08:14 UTC, 352671669 commented on dev_log/dev/spacesun202012301550.yaml
> +  - "IP存在性校验"在存在多个相同 IP 时会不通过
已修改

2021-01-12 08:21 UTC, homholueng approved these changes

2021-01-13 07:18 UTC, merged