minor: 新增 job 本地文件文件上传v2
Tencent/bk-sops pull request #3103
Opened 2020-12-14 12:35 UTC by feifeizhao4754

- 新功能
    - job 本地文件文件上传v2

2020-12-30 08:05 UTC, homholueng requested changes

2020-12-30 08:05 UTC, homholueng commented on pipeline_plugins/components/utils/job.py
>              time.sleep(1)
轮询 job 状态的逻辑借助 schedule 来完成吧，不要使用这个函数了，get_job_instance_log 这个函数如果没有再使用旧直接干掉吧

2021-01-12 07:41 UTC, homholueng requested changes

2021-01-12 07:41 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/push_local_files/v2_0_0.py
> +# -*- coding: utf-8 -*-
文件名还是 2.0.0 的格式，改成 v2_0

2021-01-12 08:26 UTC, homholueng approved these changes

2021-01-13 03:52 UTC, normal-wls commented
这个也提到3.6.x_dev分支

2021-01-13 03:52 UTC, normal-wls commented on pipeline_plugins/components/collections/sites/open/job/push_local_files/v1_0_0.py
> +    form = "%scomponents/atoms/job/job_push_local_files/v1_0_0.js" % settings.STATIC_URL
v1_0.js就可以？

2021-01-13 10:38 UTC, closed without merging