feature: plugins for cc trans host to recovery
Tencent/bk-sops pull request #3114
Opened 2020-12-15 13:03 UTC by gangh

- 新功能
    - 将主机移至待回收池

2021-01-12 08:24 UTC, feifeizhao4754 requested changes

2021-01-13 03:13 UTC, gangh commented on pipeline_plugins/components/collections/sites/open/cc/transfer_to_recovery/legacy.py
> +        cc_module_select_text = "空闲机池>待回收"
此处是对应配置的待回收 标记，传给cc下对应接口的，不是向用户进行展示的哈

2021-01-13 09:19 UTC, gangh commented on pipeline_plugins/components/collections/sites/open/cc/transfer_to_recovery/legacy.py
> +    form = "%scomponents/atoms/cc/cc_transfer_to_recovery.js" % settings.STATIC_URL
已改名更新

2021-01-13 09:19 UTC, gangh commented on static/components/atoms/cc/transfer_to_recovery/v1_0.js
> +})();
已调整

2021-01-13 09:19 UTC, gangh commented on pipeline_plugins/components/static/components/atoms/cc/transfer_to_recovery/v1_0.js
> +})();
已调整

2021-01-13 12:05 UTC, feifeizhao4754 approved these changes

2021-01-13 12:06 UTC, merged