feature:添加变量值预览后台接口
Tencent/bk-sops pull request #3123
Opened 2020-12-17 11:57 UTC by normal-wls

- 新功能
    - 添加变量值预览后台接口

2020-12-30 08:20 UTC, homholueng requested changes

2020-12-30 08:20 UTC, homholueng commented on gcloud/tasktmpl3/utils.py
> +    classified_constants = calculate_constants_type(to_calculate_constants, lazy_constants)
calculate_constants_type 加一个选项控制是否需要 deepcopy 传入的 calculated 参数，默认为 True，或者不要再使用 calculate_constants_type

2020-12-30 08:20 UTC, homholueng commented on pipeline_plugins/variables/collections/sites/open/cc.py
> +            return
返回 None？

2020-12-30 08:20 UTC, homholueng commented on gcloud/tasktmpl3/utils.py
> +        constant_values[key] = str(var_value)
为类似 SetModuleInfo 类型的变量定义 __str__ 方法以适配这个地方的转换

2021-01-03 09:10 UTC, normal-wls commented on gcloud/tasktmpl3/utils.py
> +        constant_values[key] = str(var_value)
之前优化复杂类型变量返回值的时候已经在复杂变量上添加了__repr__方法，这里可以直接进行转换

2021-01-05 02:19 UTC, homholueng approved these changes

2021-01-05 02:19 UTC, merged