feature:集群筛选变量
Tencent/bk-sops pull request #3128
Opened 2020-12-18 09:26 UTC by 352671669

- 新功能
    - 集群筛选变量

2021-01-12 08:26 UTC, feifeizhao4754 requested changes

2021-01-12 09:09 UTC, 352671669 commented on pipeline_plugins/variables/query/sites/open/query.py
> +        return JsonResponse({"result": False, "data": "调用cc接口失败，message={}".format(result["message"])})
已修改

2021-01-12 09:10 UTC, 352671669 commented on static/variables/cmdb/var_set_filter_selector.js
> +                name: "集群筛选选择器",
已修改

2021-01-12 09:10 UTC, 352671669 commented on pipeline_plugins/variables/static/variables/cmdb/var_set_filter_selector.js
> +                name: "集群筛选选择器",
已修改

2021-01-12 09:10 UTC, 352671669 commented on pipeline_plugins/variables/collections/sites/open/cmdb/var_set_filter_selector.py
> +            err_msg = "调用 cc.search_set 接口获取集群失败, kwargs={kwargs}, result={result}".format(kwargs=kwargs, result=result)
已修改

2021-01-13 08:52 UTC, feifeizhao4754 approved these changes

2021-01-13 08:52 UTC, merged