feature: 快速分发文件2.0
Tencent/bk-sops pull request #3149
Opened 2020-12-24 02:49 UTC by 352671669

- 新功能
    - JOB-快速分发文件2.0
    - 支持配置多个目标路径
    - 支持分发到非当前业务下的目标 IP
    - 支持限速配置

2021-01-12 08:57 UTC, feifeizhao4754 requested changes

2021-01-12 08:57 UTC, feifeizhao4754 commented on pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
> +                job_timeout = data.get_one_of_inputs("job_timeout")
job_timeout  可以提取到for外面

2021-01-12 08:57 UTC, feifeizhao4754 commented on pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
> +        return super(JobFastPushFileService, self).schedule(data, parent_data, callback_data)
这里pipline批量回调会有接收不到结果的问题，需要主动请求结果,可以参考下本地多文件上传的插件

2021-01-12 09:01 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
> +                    for ip in plat_ip:
已修改

2021-01-12 09:02 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
> +                job_timeout = data.get_one_of_inputs("job_timeout")
已修改

2021-01-14 08:29 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
> +        return super(JobFastPushFileService, self).schedule(data, parent_data, callback_data)
已修改

2021-01-19 03:15 UTC, feifeizhao4754 approved these changes

2021-01-19 04:04 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
> +        client.set_bk_api_ver("v2")
已修改

2021-01-19 04:06 UTC, feifeizhao4754 approved these changes

2021-01-19 04:06 UTC, feifeizhao4754 commented on pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
> +            return False
这里退出，不会进入调度对已经上传请求成功的job_id进行查询
会使用户疑惑以为有job_id的就是上传成功的。
而不知道上传成功了的作业的执行结果 。

2021-01-19 04:07 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
> +        # 循环请求接口
已修改

2021-01-19 04:07 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
> +        data.outputs.client = client
已删除

2021-01-19 04:33 UTC, feifeizhao4754 approved these changes

2021-01-19 04:33 UTC, feifeizhao4754 commented on pipeline_plugins/components/collections/sites/open/job/fast_push_file/v2_0.py
> +        for index, job_result in enumerate(job_result_list):
job_result= resp["result"]["result"] 
第一层result 是批量执行函数的结果，第二层result才请求结果的result

2021-01-21 06:22 UTC, merged