minor:新增任务、模版记录流水功能
Tencent/bk-sops pull request #3168
Opened 2020-12-29 02:32 UTC by feifeizhao4754

- 新功能
    -新增任务、模版记录流水功能

2020-12-30 09:06 UTC, homholueng requested changes

2020-12-30 09:06 UTC, homholueng commented on gcloud/contrib/operate_record/core.py
> +            return OPERATE_MODEL[self.record_type].objects.get(pk=instance_id)
这里如果能够用 filter() + only() 的形式代替尽量使用 filter + only, get 操作会把所有字段（包括不需要的）都读出来

2021-01-03 17:33 UTC, normal-wls commented on gcloud/tasktmpl3/resources.py
> +        use_in="detail",
这里应该把行末的逗号去掉就可以缩成一行？

2021-01-03 17:33 UTC, normal-wls commented on gcloud/contrib/operate_record/core.py
> +                    raise KeyError("get instance_id failed!")
这里的提示建议加上函数名等信息

2021-01-03 17:33 UTC, normal-wls commented on gcloud/contrib/operate_record/core.py
> +    def __init__(self, record_type, action, source, result, args, kwargs):
这个地方的args[0]要求是request？这样的话这个Record看上去是只支持记录views类型的流水。建议在适当的位置添加说明。

2021-01-03 17:33 UTC, normal-wls commented on gcloud/contrib/operate_record/core.py
> +RECORD_MODEL = {
这一部分感觉可以统一放到constants中

2021-01-03 17:33 UTC, normal-wls commented on gcloud/contrib/operate_record/core.py
> +        default_res, source_data = "none", [self.kwargs]
这里为什么是“none”而不是None呢

2021-01-08 13:23 UTC, feifeizhao4754 commented on gcloud/contrib/operate_record/core.py
> +                node_data = instance_obj.get_node_detail(node_id, self.operator)
pipeline_api.get_status_tree(node_id)["name"]

2021-01-11 04:00 UTC, feifeizhao4754 commented on gcloud/contrib/operate_record/core.py
> +            return OPERATE_MODEL[self.record_type].objects.get(pk=instance_id)
这里需要get_instance_obj 返回是一个实例对象

2021-01-11 04:05 UTC, feifeizhao4754 commented on gcloud/contrib/operate_record/core.py
> +    def __init__(self, record_type, action, source, result, args, kwargs):
没有明确要求，会在args和kwagrs中寻找request象，支持views和tastypie中bundle对象

2021-01-12 08:00 UTC, homholueng requested changes

2021-01-12 08:00 UTC, homholueng commented on gcloud/contrib/operate_record/core.py
> +            return OPERATE_MODEL[self.record_type].objects.get(pk=instance_id)
目前看来只有 need_save_info 中使用到了 get_instance_obj 返回的数据，而且只用到了部分，get_instance_obj 只有模块内部使用返回的格式可以调整，get 操作会把所有的行数据读取出来，造成部分无效 IO

2021-01-13 03:59 UTC, normal-wls approved these changes

2021-02-26 03:27 UTC, homholueng requested changes
去掉所有 name 保存的逻辑，会存在修改扩散的问题

2021-03-02 04:00 UTC, homholueng approved these changes

2021-03-02 04:00 UTC, merged