fixbug: job执行作业插件全局变量勾选后，刷新全局变量按钮不生效
Tencent/bk-sops pull request #3177
Opened 2020-12-30 03:29 UTC by 352671669

- bug fix
    - job执行作业插件全局变量勾选后，刷新全局变量按钮不生效

2021-01-12 08:53 UTC, feifeizhao4754 requested changes

2021-01-12 08:53 UTC, feifeizhao4754 commented on pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
>                      text: '刷新全局变量',
国际化

2021-01-12 08:53 UTC, feifeizhao4754 commented on static/components/atoms/job/job_execute_task.js
>                      text: '刷新全局变量',
国际化

2021-01-12 08:56 UTC, 352671669 commented on pipeline_plugins/components/static/components/atoms/job/job_execute_task.js
>                      text: '刷新全局变量',
已修改

2021-01-12 08:56 UTC, 352671669 commented on static/components/atoms/job/job_execute_task.js
>                      text: '刷新全局变量',
已修改

2021-01-13 08:49 UTC, feifeizhao4754 approved these changes

2021-01-13 12:07 UTC, feifeizhao4754 approved these changes

2021-01-13 12:07 UTC, merged