feature: 企业微信-发送消息插件支持发送 Markdown 格式消息
Tencent/bk-sops pull request #3181
Opened 2020-12-30 08:13 UTC by 352671669

- 新功能
    - 企业微信-发送消息插件支持发送 Markdown 格式消息

2020-12-30 09:16 UTC, homholueng requested changes

2020-12-30 09:16 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/v1_0.py
> +            ),
inputs_format 中添加 msgtype

2020-12-30 09:18 UTC, homholueng requested changes

2020-12-30 09:18 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/v1_0.py
> +                    "msgtype": msgtype,
markdown 类型的消息格式与text类型格式发送协议不一样

2020-12-31 06:20 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/v1_0.py
> +                    "msgtype": msgtype,
已按照文档修改

2020-12-31 06:20 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/wechat_work/wechat_work_send_message/v1_0.py
> +            ),
已修改

2021-01-13 12:16 UTC, homholueng approved these changes

2021-01-13 12:16 UTC, merged