feature:带导入表格表单配置分页选项
Tencent/bk-sops pull request #3188
Opened 2020-12-31 02:17 UTC by 352671669

- 新功能
    - 带导入表格表单配置分页选项

2021-01-12 07:04 UTC, homholueng requested changes

2021-01-12 07:04 UTC, homholueng commented on dev_log/dev/spacesun_202012301013.yaml
> +  - 带导入表格表单配置分页选项
devlog 中写清楚哪些插件的表格中添加了分页配置

2021-01-12 08:12 UTC, 352671669 commented on dev_log/dev/spacesun_202012301013.yaml
> +  - 带导入表格表单配置分页选项
已修改

2021-01-13 12:15 UTC, homholueng approved these changes

2021-01-13 12:15 UTC, merged