feature:快速执行脚本插件支持跨业务执行脚本
Tencent/bk-sops pull request #3200
Opened 2021-01-05 02:31 UTC by 352671669

- 新功能
    - 快速执行脚本插件支持跨业务执行脚本

2021-01-06 02:26 UTC, homholueng requested changes

2021-01-06 02:26 UTC, homholueng commented on dev_log/dev/spacesun_202101051024.yaml
> +  - 快速执行脚本插件支持跨业务执行脚本快速执行脚
日志不完整

2021-01-06 02:26 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
> +            for ip_str in original_ip_list.split("\n"):
这里直接用正则来匹配就好，不需要强制通过换行来分隔

2021-01-06 12:59 UTC, 352671669 commented on dev_log/dev/spacesun_202101051024.yaml
> +  - 快速执行脚本插件支持跨业务执行脚本快速执行脚
已修改

2021-01-06 12:59 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/job/fast_execute_script/v1_0.py
> +            for ip_str in original_ip_list.split("\n"):
已修改

2021-01-12 06:44 UTC, homholueng approved these changes

2021-01-12 06:44 UTC, homholueng commented on dev_log/dev/spacesun_202101051024.yaml
> +  - "快速执行脚本插件支持跨业务执行脚本快速执行脚本"
log 信息还是有问题：快速执行脚本插件支持跨业务执行脚本

2021-01-12 06:45 UTC, homholueng requested changes
see discussion

2021-01-12 07:42 UTC, 352671669 commented on dev_log/dev/spacesun_202101051024.yaml
> +  - "快速执行脚本插件支持跨业务执行脚本快速执行脚本"
已修改

2021-01-12 08:18 UTC, homholueng approved these changes

2021-01-12 08:18 UTC, merged