feature:JOB-快速分发文件添加“IP存在性校验”选项
Tencent/bk-sops pull request #3201
Opened 2021-01-05 02:49 UTC by 352671669

- 新功能
    - JOB-快速分发文件添加“IP存在性校验”选项

2021-01-06 02:31 UTC, homholueng requested changes

2021-01-06 02:31 UTC, homholueng commented on pipeline_plugins/components/utils/sites/open/utils.py
> +    difference_ip_list = set(input_ip_list).difference(set([ip_item["ip"] for ip_item in ip_list]))
original_ip_list 和 ip_list 类型保持保持一致，即都是 IP 文本的列表，

2021-01-06 09:12 UTC, 352671669 commented on pipeline_plugins/components/utils/sites/open/utils.py
> +    difference_ip_list = set(input_ip_list).difference(set([ip_item["ip"] for ip_item in ip_list]))
已修改

2021-01-12 02:35 UTC, homholueng approved these changes

2021-01-12 02:35 UTC, merged