improvement:JOB 系列插件获取执行日志使用 V3 接口
Tencent/bk-sops pull request #3204
Opened 2021-01-05 12:23 UTC by 352671669

- 优化项
    - JOB 系列插件获取执行日志使用 V3 接口

2021-01-12 06:40 UTC, homholueng requested changes

2021-01-12 06:40 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/base.py
> +            log_text += get_job_instance_ip_log_kwargs_return["data"]["log_content"]
不要使用字符串累加的方式，用数组存储最后 "\n".join

2021-01-12 06:40 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/base.py
> +            get_job_instance_ip_log_kwargs_return = client.jobv3.get_job_instance_ip_log_kwargs(
get_job_instance_ip_log_kwargs 写错了？
应该是 get_job_instance_ip_log？

2021-01-12 07:35 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/job/base.py
> +            get_job_instance_ip_log_kwargs_return = client.jobv3.get_job_instance_ip_log_kwargs(
已修改

2021-01-12 07:36 UTC, 352671669 commented on pipeline_plugins/components/collections/sites/open/job/base.py
> +            log_text += get_job_instance_ip_log_kwargs_return["data"]["log_content"]
已修改

2021-01-13 12:15 UTC, homholueng approved these changes

2021-01-13 12:15 UTC, merged