bugfix:筛选规则中没有对空闲机的筛选规则时，筛选为空的情况
Tencent/bk-sops pull request #3224
Opened 2021-01-13 12:49 UTC by JavHou

bugfix:筛选规则中没有对空闲机的筛选规则时，筛选为空的情况

2021-01-14 09:20 UTC, homholueng requested changes

2021-01-14 09:20 UTC, homholueng commented on pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
> +    biz_internal_module = set(BIZ_INTERNAL_MODULE) & set(service_template_names)
从代码意义上看，这里叫做 filter_biz_internal_module 更明确

2021-01-14 09:20 UTC, homholueng commented on pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
> +        biz_internal_module = set(BIZ_INTERNAL_MODULE) & set(select_biz_internal_module)
这里再取一次交集的意义是？

2021-01-14 09:20 UTC, homholueng commented on pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
> +
这个函数的筛选规则已经很复杂了，在函数注释中添加处理逻辑框架的描述

2021-01-14 09:20 UTC, homholueng commented on pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
> +    if not biz_internal_module and BIZ_INTERNAL_SET not in filter_set_names:
如果 set_list 选择了空闲机集群，这里的逻辑就覆盖不到了吧？

2021-01-18 03:55 UTC, JavHou commented on pipeline_plugins/variables/collections/sites/open/cmdb/var_cmdb_set_module_ip_selector.py
> +        biz_internal_module = set(BIZ_INTERNAL_MODULE) & set(select_biz_internal_module)
为了获取之前选择到的选择到的空闲机model name，注释已经加上

2021-01-29 06:42 UTC, homholueng approved these changes

2021-01-30 10:35 UTC, merged