improvement:  添加业务下最大周期任务数限制，默认为100, 支持管理员配置。
Tencent/bk-sops pull request #3324
Opened 2021-02-22 09:27 UTC by normal-wls

- 优化项
    - 添加业务下最大周期任务数限制，默认为100, 支持管理员配置。

2021-03-18 13:02 UTC, homholueng commented on gcloud/apigw/views/create_periodic_task.py
> +        max_periodic_task_num = ProjectConfig.objects.get(project_id=project.id).max_periodic_task_num
.only("max_periodic_task_num"). max_periodic_task_num

2021-03-18 13:03 UTC, homholueng requested changes

2021-03-18 13:03 UTC, homholueng commented on gcloud/apigw/views/create_periodic_task.py
> +        return JsonResponse({"result": False, "message": message, "code": err_code.UNKNOWN_ERROR.code})
UNKNOWN_ERROR?

2021-03-18 13:03 UTC, homholueng commented on gcloud/periodictask/resources.py
> +            max_periodic_task_num = ProjectConfig.objects.get(project_id=project.id).max_periodic_task_num
.only("max_periodic_task_num"). max_periodic_task_num

2021-03-22 11:55 UTC, normal-wls commented on gcloud/periodictask/resources.py
> +            max_periodic_task_num = ProjectConfig.objects.get(project_id=project.id).max_periodic_task_num
> .only("max_periodic_task_num"). max_periodic_task_num

get已得到object非queryset，没办法再only

2021-03-22 11:55 UTC, normal-wls commented on gcloud/apigw/views/create_periodic_task.py
> +        max_periodic_task_num = ProjectConfig.objects.get(project_id=project.id).max_periodic_task_num
> .only("max_periodic_task_num"). max_periodic_task_num

get已得到object非queryset，没办法再only

2021-03-26 07:05 UTC, homholueng approved these changes

2021-03-26 08:08 UTC, merged