improvement: 依赖第三方版本升级(blueapps,pipeline,celery)
Tencent/bk-sops pull request #3398
Opened 2021-03-17 03:51 UTC by normal-wls

- 优化项
    - 依赖第三方版本升级(blueapps,pipeline,celery)

2021-03-19 02:51 UTC, homholueng requested changes

2021-03-19 02:51 UTC, homholueng commented on config/default.py
> +    CELERY_TASK_SERIALIZER = "pickle"
为何用 pickle 不用 json，pickle 有安全风险

2021-03-19 02:51 UTC, homholueng commented on gcloud/core/models.py
> +    business = models.ForeignKey(Business, on_delete=models.CASCADE)
这里为什么要加上级联删除配置？

2021-03-19 02:51 UTC, homholueng commented on gcloud/core/views.py
> +    is_match = bk_token == request.session.get("bk_token")
这里使用的是哪个 backend 来存储的 seesion？

2021-03-19 02:51 UTC, homholueng commented on gcloud/periodictask/models.py
> +    task = models.ForeignKey(PipelinePeriodicTask, verbose_name=_("pipeline 层周期任务"), on_delete=models.CASCADE)
为何要级联删除

2021-03-19 02:51 UTC, homholueng commented on gcloud/utils/cache.py
> +from threading import Lock
为何不用读写锁

2021-03-19 02:51 UTC, homholueng commented on pipeline/README.md
> -[3.x 版本升级说明](./docs/user_guide_3.x_upgrade.md)
为何删除了这些文档

2021-03-19 02:51 UTC, homholueng commented on pipeline_web/core/models.py
> +    node = models.ForeignKey(NodeInTemplate, verbose_name=_("流程模板节点"), on_delete=models.CASCADE)
同上

2021-03-19 03:12 UTC, normal-wls commented on gcloud/core/models.py
> +    business = models.ForeignKey(Business, on_delete=models.CASCADE)
django1.11默认配置

2021-03-19 10:12 UTC, normal-wls commented on gcloud/periodictask/models.py
> +    task = models.ForeignKey(PipelinePeriodicTask, verbose_name=_("pipeline 层周期任务"), on_delete=models.CASCADE)
django1.11默认配置

2021-03-19 10:12 UTC, normal-wls commented on pipeline_web/core/models.py
> +    node = models.ForeignKey(NodeInTemplate, verbose_name=_("流程模板节点"), on_delete=models.CASCADE)
django1.11默认配置

2021-03-22 13:15 UTC, normal-wls commented on gcloud/core/views.py
> +    is_match = bk_token == request.session.get("bk_token")
> 这里使用的是哪个 backend 来存储的 seesion？

django.contrib.sessions，跟之前版本一致，基于数据库的会话

2021-03-22 13:33 UTC, normal-wls commented on gcloud/utils/cache.py
> +from threading import Lock
> 为何不用读写锁

此处保持与django2的LocMemCache实现一致

2021-03-25 07:16 UTC, homholueng approved these changes

2021-03-25 07:17 UTC, merged