feature: 流程执行方案批量操作接口&& 克隆模版支持执行方案克隆
Tencent/bk-sops pull request #3428
Opened 2021-03-25 08:57 UTC by feifeizhao4754

- 新功能
    - 新增模版编辑页面添加执行方案
    - 克隆模版增加执行方案克隆

2021-03-31 01:35 UTC, homholueng requested changes

2021-03-31 01:35 UTC, homholueng commented on gcloud/tasktmpl3/apis/drf/viewsets/template_scheme.py
> +        template = TaskTemplate.objects.get(pk=template_id, project_id=project_id)
```filter(**kwargs).only("id").first().id```

2021-03-31 01:35 UTC, homholueng commented on gcloud/tasktmpl3/apis/drf/viewsets/template_scheme.py
> +        if not template_id or not current_schemes:
这个校验可以放在 serializer 中做？

2021-03-31 01:35 UTC, homholueng commented on gcloud/tasktmpl3/apis/drf/viewsets/template_scheme.py
> +        # 批量创建scheme
先创建再删除会不会出现同名方案 `unique_id` 冲突的情况？

2021-04-01 08:48 UTC, feifeizhao4754 commented on gcloud/tasktmpl3/apis/drf/viewsets/template_scheme.py
> +        template = TaskTemplate.objects.get(pk=template_id, project_id=project_id)
filter(template_id=template_id, project_id=project_id).only("id").first() .pipeline_template.id

2021-04-02 02:39 UTC, normal-wls commented on gcloud/resources/urls.py
> +urlpatterns = [url(r"^api/v3/", include(drf_router.urls)), url(r"^api/", include(v3_api.urls))]
如果不走旧的TemplateSchemeResource了可以先注释掉，不需要调换两者的顺序

2021-04-02 07:28 UTC, feifeizhao4754 commented on gcloud/tasktmpl3/apis/drf/viewsets/template_scheme.py
> +        # 批量创建scheme
批量逻辑，全删除后，新建执行方案

2021-04-06 02:32 UTC, homholueng requested changes

2021-04-06 02:32 UTC, homholueng commented on gcloud/tasktmpl3/apis/drf/viewsets/template_scheme.py
> +        return TaskTemplate.objects.filter(**_filter).only("id").first().pipeline_template.id
only pipeline_template__id

2021-04-06 07:43 UTC, feifeizhao4754 commented on gcloud/tasktmpl3/apis/drf/viewsets/template_scheme.py
> +        return TaskTemplate.objects.filter(**_filter).only("id").first().pipeline_template.id
only("pipeline_template__id").first().pipeline_template.id

2021-04-07 02:47 UTC, homholueng approved these changes

2021-04-07 02:47 UTC, merged