improvement：对于插件和变量相关接口请求返回为False情况添加统一处理逻辑
Tencent/bk-sops pull request #3432
Opened 2021-03-26 06:38 UTC by normal-wls

improvement:
  - 对于插件和变量相关接口请求返回为False情况添加统一处理逻辑

2021-04-14 09:19 UTC, homholueng requested changes

2021-04-14 09:19 UTC, homholueng commented on api/utils/request.py
> +            raise PluginApiRequestError(message)
这里直接抛出 PluginApiRequestError 是否合适？有些非插件类型的接口如果也用到了这个工具呢

2021-04-14 09:19 UTC, homholueng commented on pipeline/core/flow/activity/service_activity.py
> +            self.data.set_outputs("ex_data", e)
这里如果捕获了无权限的错误也没办法暴露出申请 url 吧？

2021-04-14 09:19 UTC, homholueng commented on pipeline/core/flow/activity/service_activity.py
> +            result = False
pipeline 相关改动同步到 bamboo-pipeline 及 bamboo-engine

2021-04-27 09:29 UTC, normal-wls commented on pipeline/core/flow/activity/service_activity.py
> +            self.data.set_outputs("ex_data", e)
如果是无权限情况，按照约定会在接口返回中带上申请url，会在ex_data中显示

2021-05-07 06:47 UTC, homholueng approved these changes

2021-05-07 06:50 UTC, merged