feature:新增全业务快速分发文件，支持批量分发
Tencent/bk-sops pull request #3468
Opened 2021-04-07 08:53 UTC by feifeizhao4754

- 新功能
    - 新增全业务快速分发文件，支持批量分发

2021-04-21 03:40 UTC, homholueng requested changes

2021-04-21 03:40 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_0.py
> +                job_target_path = attr["job_target_path"].replace("[FILESRCIP]", source["ip_list"][0]["ip"])
`[FILESRCIP]` 语法是 JOB 支持的，可以不用再标准运维侧支持这个语法了🤣

2021-04-21 03:40 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_0.py
> +        data.outputs.final_res = task_count == len(job_instance_id_list)
考虑几种情况的失败处理🤔

1. 部分请求失败，用户如何处理？
2. 部分分发失败，用户如何处理？
3. 部分请求失败，请求成功的部分分发失败，用户如何处理？

2021-05-07 08:04 UTC, feifeizhao4754 commented on pipeline_plugins/components/collections/sites/open/job/all_biz_fast_push_file/v1_0.py
> +        data.outputs.final_res = task_count == len(job_instance_id_list)
这里有调用的父类JobScheduleService的schedule对数据进行处理

2021-05-08 03:04 UTC, homholueng approved these changes

2021-05-08 03:04 UTC, merged