minor: job系列插件IP参数过滤优化
Tencent/bk-sops pull request #3489
Opened 2021-04-14 13:42 UTC by feifeizhao4754

- 优化项
    -  job系列插件IP参数过滤优化

2021-04-21 03:29 UTC, homholueng requested changes

2021-04-21 03:29 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/__init__.py
> +from .base import *  # noqa
base 一定要 import * 么

2021-04-21 03:29 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/base.py
> +    if len(ip_list) != len(set(input_ip_set)) or not ip_list:
`len(ip_list) != len(set(input_ip_set))` 和 `ip_list` 为空这两种情况的错误提示应该区分开

2021-04-21 03:29 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/base.py
> +    """
ip_is_exist 参数没有使用？

2021-05-08 06:56 UTC, feifeizhao4754 commented on pipeline_plugins/components/collections/sites/open/job/base.py
> +    """
不使用，ip会都被get_ip_by_regex筛选

2021-05-24 06:40 UTC, homholueng requested changes

2021-05-24 06:40 UTC, homholueng commented on pipeline_plugins/components/utils/sites/open/utils.py
> +    logger_handle.info("from cmdb get valid ip list:{}, user input ip list:{}".format(ip_list, input_ip_set))
1. 这里的日志对于跨业务的情况来说是不准确的

2021-05-24 08:15 UTC, homholueng approved these changes

2021-05-24 08:15 UTC, merged