improvement:  全局变量类型添加说明
Tencent/bk-sops pull request #3493
Opened 2021-04-16 06:30 UTC by v-xugzhou

- 优化项
    - 全局变量类型添加说明

2021-04-16 07:16 UTC, fannluo commented on frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
> +                    this.variableConfig = result || {}
插件配置项的前端有做缓存，缓存只包含变量的插件配置项，切换变量类型后再切回就显示不了变量的说明了

2021-04-22 03:14 UTC, fannluo requested changes

2021-04-22 03:14 UTC, fannluo commented on frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
> +                    <div class="variable-type-desc">{{ variableConfig.description }}</div>
- 后台返回的字段名称是 `description` 吗，有没有确认过
- 考虑描述不存在的情况

2021-04-22 03:14 UTC, fannluo commented on frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
> +                return data
如果有匹配打对应类型的变量，直接返回描述信息字段，其他情况统一返回空字符串

2021-04-22 03:39 UTC, v-xugzhou commented on frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
> +                    <div class="variable-type-desc">{{ variableConfig.description }}</div>
已和皓哥确认是description字段名

2021-04-22 07:08 UTC, merged