Chenrb v3.6.x dev
Tencent/bk-sops pull request #3561
Opened 2021-05-13 02:33 UTC by chenrb

- 新功能
    - 新增 全业务执行作业方案原子 功能
- 优化项
    - 修改batch_request传参，适配jobv3接口
- bug fix
    - 修复IP正则校验问题

2021-05-20 06:59 UTC, normal-wls requested changes

2021-05-20 07:40 UTC, chenrb commented on pipeline_plugins/components/utils/sites/open/utils.py
> +ip_re = r"(?<!\d)((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)(?!\d)"
![image](https://user-images.githubusercontent.com/27913541/118938786-982df300-b981-11eb-93dc-828cc77df2e2.png)

2021-05-20 09:27 UTC, normal-wls requested changes

2021-05-20 09:27 UTC, normal-wls commented on pipeline_plugins/components/static/components/atoms/job/all_biz_execute_job_plan/all_biz_execute_job_plan_output.js
> +})();
static目录需要上传静态文件

2021-05-20 09:27 UTC, normal-wls commented on pipeline_plugins/components/static/components/atoms/job/all_biz_execute_job_plan/all_biz_execute_job_plan.js
> +})();
static目录需要上传静态文件

2021-05-31 02:25 UTC, normal-wls requested changes

2021-05-31 02:25 UTC, normal-wls commented on pipeline_plugins/components/utils/sites/open/utils.py
> +ip_re = r"(?<!\d)((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)(?!\d)"
这个地方不应该吞掉10.2.1.25的ip，而只是应该过滤不合法ip

2021-05-31 02:25 UTC, normal-wls commented on gcloud/utils/ip.py
> +ip_pattern = re.compile(r"(?<!=\d)((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)(?!\d)")
看看截图的回复，建议添加一下对应的单元测试

2021-05-31 02:25 UTC, normal-wls commented on pipeline_plugins/components/utils/common.py
> +ip_re = r"(?<!=\d)((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)(?!\d)"
看看截图的回复，建议添加一下对应的单元测试

2021-05-31 02:25 UTC, normal-wls commented on pipeline_plugins/components/utils/sites/open/utils.py
> +ip_re = r"(?<!\d)((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)(?!\d)"
建议添加对应的单元测试

2021-09-28 12:58 UTC, closed without merging