feature: 新增条件并行网关
Tencent/bk-sops pull request #3568
Opened 2021-05-13 11:04 UTC by AmosLeee

- 新功能
    - 新增条件并行网关

2021-05-17 02:40 UTC, homholueng requested changes

2021-05-17 02:40 UTC, homholueng commented on pipeline_web/parser/schemas.py
> +                        {
1. gcloud.tasktmpl3.utils.analysis_pipeline_constants_ref 中的变量引用分析也需要增加对条件并行网关的支持

2021-05-26 01:29 UTC, fannluo approved these changes

2021-05-26 02:55 UTC, homholueng approved these changes

2021-05-26 02:56 UTC, merged