【优化】JOB 分发本地文件 2.0 版本支持配置超时时间(V3.6.X)
Tencent/bk-sops pull request #3780
Opened 2021-07-15 05:28 UTC by rwwg

- 优化项
    - JOB 分发本地文件 2.0 版本支持配置超时时间(V3.6.X)

2021-07-15 05:28 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/bk-sops?pullRequest=3780) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-sops?pullRequest=3780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-sops?pullRequest=3780) it.</sub>

2021-07-16 06:39 UTC, homholueng requested changes

2021-07-16 06:39 UTC, homholueng commented on pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
> +        {
static/components/atoms/job/job_push_local_files/v2_0.js 
也要同步改动下

2021-07-16 07:24 UTC, rwwg commented on pipeline_plugins/components/static/components/atoms/job/job_push_local_files/v2_0.js
> +        {
已处理

2021-07-16 11:07 UTC, homholueng approved these changes

2021-07-16 11:27 UTC, merged