feature:JOB执行作业 新版本插件 需要给每个参数加上双引号，防止空格导致变成多个参数(V3.6.X)
Tencent/bk-sops pull request #3812
Opened 2021-07-22 14:35 UTC by rwwg

- 新功能
    - feature:JOB执行作业 新版本插件 需要给每个参数加上双引号，防止空格导致变成多个参数(V3.6.X)

2021-08-23 12:40 UTC, normal-wls requested changes

2021-08-23 12:40 UTC, normal-wls commented on pipeline_plugins/components/collections/sites/open/job/execute_task/base.py
> +    def execute(self, data, parent_data):
这里抽象出来的execute函数好像并没有复用到？

2021-08-23 12:40 UTC, normal-wls commented on pipeline_plugins/components/collections/sites/open/job/execute_task/v1_0.py
> +    def execute(self, data, parent_data):
这里和抽象出来的execute有何不同，是否可以复用

2021-08-24 07:37 UTC, rwwg commented on pipeline_plugins/components/collections/sites/open/job/execute_task/base.py
> +    def execute(self, data, parent_data):
确实没用到，已修正

2021-08-24 07:37 UTC, rwwg commented on pipeline_plugins/components/collections/sites/open/job/execute_task/v1_0.py
> +    def execute(self, data, parent_data):
execute不可以复用

2021-08-24 13:33 UTC, normal-wls requested changes

2021-08-24 13:33 UTC, normal-wls commented on pipeline_plugins/components/collections/sites/open/job/execute_task/legacy.py
> +        return super(JobExecuteTaskService, self).outputs_format()
如果只是单纯用到父类的对应函数，可以不重载这个函数

2021-08-25 06:47 UTC, normal-wls approved these changes

2021-08-25 06:56 UTC, closed without merging