feature: IP选择器支持手动输入解析
Tencent/bk-sops pull request #3848
Opened 2021-08-12 08:03 UTC by normal-wls

- 新功能
    -  IP选择器支持手动输入解析

2021-08-19 08:31 UTC, homholueng requested changes

2021-08-19 08:31 UTC, homholueng commented on pipeline_plugins/cmdb_ip_picker/utils.py
> +    def __init__(self, input_type, raw_data, request_kwargs, gen_kwargs):
参数说明文档

2021-08-19 08:31 UTC, homholueng commented on pipeline_plugins/cmdb_ip_picker/utils.py
> +        result = batch_request(client.cc.search_dynamic_group, self.request_kwargs, limit=200)
search_dynamic_group 有 condition 参数支持通过 name 过滤

2021-08-19 08:31 UTC, homholueng commented on pipeline_plugins/cmdb_ip_picker/utils.py
> +        # 去除包含关系的拓扑路径，只保持最高层级结构
函数文档，对输入数据和输出数据举例说明

2021-08-21 08:49 UTC, normal-wls commented on pipeline_plugins/cmdb_ip_picker/utils.py
> +        result = batch_request(client.cc.search_dynamic_group, self.request_kwargs, limit=200)
condition无法支持多值搜索

2021-08-21 08:49 UTC, normal-wls commented on pipeline_plugins/cmdb_ip_picker/utils.py
> +        result = batch_request(client.cc.search_dynamic_group, self.request_kwargs, limit=200)
> search_dynamic_group 有 condition 参数支持通过 name 过滤

condition无法支持多值搜索

2021-08-23 08:28 UTC, homholueng approved these changes

2021-08-23 08:28 UTC, merged