feature:create_task接口支持选择执行节点
Tencent/bk-sops pull request #3893
Opened 2021-08-18 09:30 UTC by yovafeng

- feature
    - create_task接口支持选择执行节点

2021-08-19 02:45 UTC, homholueng requested changes

2021-08-19 02:45 UTC, homholueng commented on gcloud/apigw/schemas.py
>          "flow_type": {"type": "string", "enum": list(TASK_FLOW.keys())},
补充 dev log

2021-08-19 02:45 UTC, homholueng commented on gcloud/apigw/views/utils.py
> +def get_exclude_nodes_by_execute_nodes(execute_nodes, template):
这个函数只有  create_task 模块使用到，放在 create_task 模块中即可，暂时不需要提取到 utils 中

2021-08-19 02:45 UTC, homholueng commented on gcloud/apigw/views/utils.py
> +    all_nodes = []
all_nodes 不是所有执行方案的集合，而是流程中所有任务节点和子流程节点的集合

2021-08-19 02:45 UTC, homholueng commented on gcloud/tests/apigw/views/test_create_task.py
>  from gcloud.tests.mock import *  # noqa
补充新的测试用例

2021-08-19 08:37 UTC, homholueng requested changes

2021-08-19 08:37 UTC, homholueng commented on gcloud/apigw/views/create_task.py
> +    execute_nodes = [node for node in execute_nodes if node in all_nodes]
in list：O(n)
in set：O(1)

2021-08-19 08:37 UTC, homholueng commented on gcloud/apigw/views/create_task.py
> +        if act_data[PE.type] == PE.SubProcess:
这里不需要递归下去，只允许排除最上层节点

2021-08-19 08:37 UTC, homholueng commented on gcloud/apigw/views/create_task.py
> +    exclude_nodes = [node for node in all_nodes if node not in execute_nodes]
set.intersect

2021-08-19 08:37 UTC, homholueng commented on gcloud/tests/apigw/views/test_create_task.py
> +                        "execute_task_nodes_id": "execute_task_nodes_id",
这里传入的不是实际的测试参数么?

2021-08-19 08:43 UTC, yovafeng commented on gcloud/apigw/views/create_task.py
> +    execute_nodes = [node for node in execute_nodes if node in all_nodes]
solved

2021-08-19 08:46 UTC, yovafeng commented on gcloud/apigw/views/create_task.py
> +        if act_data[PE.type] == PE.SubProcess:
solved

2021-08-19 09:00 UTC, yovafeng commented on gcloud/apigw/views/create_task.py
> +    exclude_nodes = [node for node in all_nodes if node not in execute_nodes]
solved

2021-08-19 09:10 UTC, yovafeng commented on gcloud/tests/apigw/views/test_create_task.py
> +                        "execute_task_nodes_id": "execute_task_nodes_id",
solved

2021-08-19 09:59 UTC, homholueng requested changes

2021-08-19 09:59 UTC, homholueng commented on gcloud/apigw/views/create_task.py
> +    for aid, act_data in list(data[PE.activities].items()):
外层加一个 list 化的意义是？

2021-08-19 09:59 UTC, homholueng commented on gcloud/apigw/views/create_task.py
> +    all_nodes = get_pipeline_node(pipeline_data)
get_pipeline_node 逻辑已经很简单了，可以不用封装成函数了

2021-08-19 09:59 UTC, homholueng commented on gcloud/tests/apigw/views/test_create_task.py
> +                        "execute_task_nodes_id": "execute_task_nodes_id",
按照接口的实现，这里应该是数组吧？

2021-09-27 08:54 UTC, homholueng approved these changes

2021-09-27 08:54 UTC, merged