feature:运营数据维度丰富
Tencent/bk-sops pull request #4417
Opened 2021-11-04 08:22 UTC by DomineCore

2021-11-05 09:11 UTC, luofann approved these changes

2021-11-05 09:11 UTC, homholueng requested changes

2021-11-05 09:11 UTC, homholueng commented on gcloud/taskflow3/models.py
> +            proj_attr_info = get_business_attrinfo(demision)
一次调用把所有属性都拉回来，不要在循环中多次调用接口

2021-11-05 09:11 UTC, homholueng commented on gcloud/taskflow3/models.py
> +                if info[demision] not in result.keys():
用 setdefault 精简这段代码

2021-11-05 09:11 UTC, homholueng commented on gcloud/tasktmpl3/models.py
> +        for tmpl in task_create_methods:
尝试用 setdefault 精简

2021-11-05 09:11 UTC, homholueng commented on gcloud/tasktmpl3/models.py
> +            # all_tasktmpl_count = self.filter(pipeline_template__id__in=tasktmpl_list).count()
无用注释删除

2021-11-05 09:11 UTC, homholueng commented on gcloud/tasktmpl3/models.py
> +            proj_attr_info = get_business_attrinfo(demision)
同上，非必要不要在循环中拉取接口

2021-11-05 09:11 UTC, homholueng commented on gcloud/tasktmpl3/models.py
> +                if info[demision] not in result.keys():
尝试用 setdefault 精简

2021-11-08 02:08 UTC, homholueng approved these changes

2021-11-08 02:10 UTC, merged