容器化分支合入主分支
Tencent/bk-sops pull request #4460
Opened 2021-11-08 13:32 UTC by normal-wls

2021-11-10 03:44 UTC, homholueng requested changes

2021-11-10 03:44 UTC, homholueng commented on app_desc.yaml
> +            - key: PIP_VERSION
调整为 21.0

2021-11-10 03:44 UTC, homholueng commented on app_desc.yaml
> +            - key: PIP_VERSION
调整为 21.0

2021-11-10 03:44 UTC, homholueng commented on app_desc.yaml
> +              value: 20.2.3
调整为 21.0

2021-11-10 03:44 UTC, homholueng commented on app_desc.yaml
> +              value: 20.2.3
调整为 21.0

2021-11-10 03:44 UTC, homholueng commented on app_desc.yaml
> +                command: gunicorn wsgi -w 7 -b :$PORT --access-logfile - --error-logfile - --access-logformat '[%(h)s] %({request_id}i)s %(u)s %(t)s "%(r)s" %(s)s %(D)s %(b)s "%(f)s" "%(a)s"' --max-r
1. 改为 `gunicorn wsgi -w $GUNICORN_WORKER_NUM -b :$PORT --access-logfile - --error-logfile - --access-logformat '[%(h)s] %({request_id}i)s %(u)s %(t)s "%(r)s" %(s)s %(D)s %(b)s "%(f)s" "%(a)s"' --max-requests=500 -k gthread --threads $GUNICORN_THREAD_NUM`
2. 增加 `GUNICORN_WORKER_NUM` 与 `GUNICORN_THREAD_NUM` 这两个环境变量

2021-11-10 03:44 UTC, homholueng commented on app_desc.yaml
> +                command: gunicorn wsgi -w 8 -b :$PORT --access-logfile - --error-logfile - --access-logformat '[%(h)s] %({request_id}i)s %(u)s %(t)s "%(r)s" %(s)s %(D)s %(b)s "%(f)s" "%(a)s"' --max-r
1. 改为 `gunicorn wsgi -w $GUNICORN_WORKER_NUM -b :$PORT --access-logfile - --error-logfile - --access-logformat '[%(h)s] %({request_id}i)s %(u)s %(t)s "%(r)s" %(s)s %(D)s %(b)s "%(f)s" "%(a)s"' --max-requests=500 -k gthread --threads $GUNICORN_THREAD_NUM`
2. 增加 `GUNICORN_WORKER_NUM` 与 `GUNICORN_THREAD_NUM` 这两个环境变量

2021-11-10 03:44 UTC, homholueng commented on app_desc.yaml
> +                command: celery worker -A blueapps.core.celery -P gevent -Q api_task_queue_service_schedule_priority -n api_task_schedule_worker@%h -c 100 -l info --maxtasksperchild=50
`-P gevent` 全部调整为 `-P threads`

2021-11-11 07:08 UTC, normal-wls commented on app_desc.yaml
> +            - key: PIP_VERSION
已确认20.2.3支持

2021-11-11 11:19 UTC, homholueng approved these changes

2021-11-11 11:19 UTC, merged