添加系统内置全局变量taskUrl
Tencent/bk-sops pull request #4486
Opened 2021-11-11 08:54 UTC by DomineCore

2021-11-30 07:23 UTC, homholueng requested changes

2021-11-30 07:23 UTC, homholueng commented on gcloud/taskflow3/domains/context.py
> +                "name": _("任务Url"),
任务URL

2021-11-30 07:23 UTC, homholueng commented on gcloud/taskflow3/domains/context.py
> +            settings.BKPAAS_SERVICE_ADDRESSES_BKSAAS.rstrip("/")
这个获取域名的逻辑要兼容三种情况：
1. V2 版本 PaaS
2. 容器化版本 V3 PaaS
3. 上云版 V3 PaaS

2021-11-30 07:48 UTC, DomineCore commented on gcloud/taskflow3/domains/context.py
> +            settings.BKPAAS_SERVICE_ADDRESSES_BKSAAS.rstrip("/")
已替换为BK_SOPS_HOST

2021-11-30 09:30 UTC, homholueng requested changes

2021-12-01 03:34 UTC, homholueng approved these changes

2021-12-01 03:37 UTC, merged