计划任务创建失败时需要添加用户通知
Tencent/bk-sops pull request #4513
Opened 2021-11-15 10:05 UTC by ywywZhou

计划任务创建失败时需要添加用户通知

2021-11-15 12:51 UTC, luofann requested changes

2021-11-15 12:51 UTC, luofann commented on frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
> +                                </NotifyTypeConfig>
- 把这两个表单项用bk-form封装，作为整体引入，这种使用方式有点奇怪。
- label 可以通过props传入
- 样式的差异在组件使用的地方用css覆盖
- 流程模版编辑配置通知的地方没有用公共组件？

2021-11-16 03:28 UTC, luofann requested changes

2021-11-16 03:28 UTC, luofann commented on frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
> +            },
不需要抛出loading的change事件了，想了下，通知相关的配置在loading状态时，保存按钮禁用的逻辑可以去掉，没有加载完成时保存，不会影响已有数据。

2021-11-16 03:28 UTC, luofann commented on frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
> +                'projectBaseInfo': state => state.template.projectBaseInfo
这个state没有用到

2021-11-16 03:28 UTC, luofann commented on frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
> +                }
formData里面只有两个确定的属性，不建议用for...of循环，直接用解构的方式，更直观一些

2021-11-16 03:28 UTC, luofann commented on frontend/desktop/src/pages/task/TaskCreate/TaskParamFill.vue
> +            onReceiverGroup (val) {
这个方法没有用到了

2021-11-16 03:28 UTC, luofann commented on frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue
> +            <bk-form-item :property="'notifyType'" :label="notifyTypeLabel">
`property="notifyType" ` 属性值是字符串就用这种写法，用变量的方式有点奇怪

2021-11-16 03:28 UTC, luofann commented on frontend/desktop/src/pages/template/TemplateEdit/TemplateSetting/NotifyTypeConfig.vue
> +                AllNotifyTypeList: [],
属性名首字母不要大写

2021-11-16 06:26 UTC, DomineCore approved these changes

2021-11-16 06:36 UTC, luofann approved these changes

2021-11-16 06:45 UTC, merged