新增任务节点超时处理功能
Tencent/bk-sops pull request #4719
Opened 2021-12-13 12:04 UTC by normal-wls

2021-12-15 03:48 UTC, homholueng requested changes

2021-12-15 03:48 UTC, homholueng commented on gcloud/taskflow3/celery/tasks.py
> +@task
配置 ignore_result

2021-12-15 03:48 UTC, homholueng commented on gcloud/taskflow3/celery/tasks.py
> +    return handler.deal_with_timeout_node(task_inst, node_id)
节点处理结果无论失败建议都打印当前时间和日志，便于追溯和排查问题

2021-12-15 03:48 UTC, homholueng commented on gcloud/taskflow3/management/commands/node_timeout_process.py
> +                self._execute_node_timeout_strategy(node)
监听处理 terminate 信号

2021-12-15 03:48 UTC, homholueng commented on gcloud/taskflow3/management/commands/node_timeout_process.py
> +        redis_inst = settings.redis_inst
这段逻辑需要保证 O(1) 复杂度

2021-12-15 03:48 UTC, homholueng commented on gcloud/taskflow3/management/commands/node_timeout_process.py
> +class Command(BaseCommand):
单元测试

2021-12-17 03:24 UTC, homholueng commented on gcloud/taskflow3/celery/tasks.py
> +    for node in nodes:
这里考虑是否要加入一个指标来记录单次超时记录会派发出去的节点数量

2021-12-17 03:24 UTC, homholueng commented on gcloud/taskflow3/celery/tasks.py
> +            kwargs={"node_id": node_id, "version": version}, queue="node_timeout", routing_key="node_timeout"
node_timeout 的队列名表意感觉不太明确，改成 `execute_node_timeout_strategy` ?

2021-12-17 03:24 UTC, homholueng commented on gcloud/taskflow3/management/commands/node_timeout_process.py
> +            redis_inst.zrem(nodes_pool, *timeout_nodes)
是否需要考虑处理 record_timeout_nodes 成功，但是 zrem 失败的情况？

2021-12-17 03:24 UTC, homholueng commented on gcloud/taskflow3/utils.py
> +def parse_node_timeout_configs(pipeline_tree: dict) -> list:
这段逻辑放在 utils 里面是否是最优的方案？单独使用一个 NodeTimeoutConfigParser 模块来处理是否更优？防止 utils 模块膨胀

2021-12-17 08:12 UTC, normal-wls commented on gcloud/taskflow3/utils.py
> +def parse_node_timeout_configs(pipeline_tree: dict) -> list:
utils中目前放置的都是parse相关函数，如果后面有类似的配置解析逻辑，可以直接基于这个函数进行修改

2021-12-20 06:38 UTC, homholueng approved these changes

2021-12-20 06:39 UTC, merged