子流程节点允许选择执行方案
Tencent/bk-sops pull request #4979
Opened 2022-01-13 13:14 UTC by wheel-w

子流程节点允许选择执行方案

2022-01-14 02:58 UTC, homholueng requested changes

2022-01-14 02:58 UTC, homholueng commented on gcloud/taskflow3/apis/django/api.py
> +def preview_task_tree_with_schemes(request):
在 gcloud.taskflow3.apis.drf.viewsets 下通过 class base view 的方式提供接口

2022-01-14 02:58 UTC, homholueng commented on gcloud/taskflow3/models.py
> +        def _sub_process_scheme_pipeline_tree(pipeline_tree):
这个逻辑是否可以在 PipelineTemplateWebWrapper.unfold_subprocess 中实现，本身就是模板维度的子流程展开操作，在 PipelineTemplateWebWrapper.unfold_subprocess 中更合理

2022-01-14 02:58 UTC, homholueng commented on gcloud/taskflow3/models.py
> +                sub_pipeline_node_data = {
这一段代码的目的是？

2022-01-14 02:58 UTC, homholueng commented on gcloud/template_base/domains/template_manager.py
> +        relation_queryset = TemplateRelationship.objects.filter(ancestor_template_id__in=pipeline_template_id_list)
是否可以考虑这种方案：
1. 删除时不清空 TemplateRelationship 中的执行方案关系
2. 在统计执行方案是否被引用时过滤掉删除标志位为真的流程
这样可以增加系统的健壮性，防止流程误删除恢复时无法手动恢复关系数据

2022-01-14 05:19 UTC, wheel-w commented on gcloud/taskflow3/models.py
> +        def _sub_process_scheme_pipeline_tree(pipeline_tree):
之前考虑过直接在unfold_subprocess里面进行操作，问题是unfold_subprocess所在的模块PipelineTemplateWebWrapper已经在taskflow3.models模块引入了，而这个逻辑需要使用taskflow3.models.preview_template_tree_with_schemes方法，两个模块不能互相引用

2022-01-14 05:53 UTC, wheel-w commented on gcloud/template_base/domains/template_manager.py
> +        relation_queryset = TemplateRelationship.objects.filter(ancestor_template_id__in=pipeline_template_id_list)
如果要考虑流程误删恢复时情况下的话，我觉得现有清空的方案的好一点
1. 如果根据删除标志位去判断的话，如果用户删除了一个流程，执行方案的引用数从1变成了0，然后删除了该执行方案，这个时候用户拿着恢复后的流程去创建任务,这个时候虽然存在无效的执行方案，用户却是感知不到的
2. 如果在恢复误删流程的时候，恢复之后，点击一次保存流程，关系数据也就恢复了，如果在恢复期间，引用的执行方案被删除了，用户也会收到报错信息，从而调整执行方案

2022-01-14 06:22 UTC, wheel-w commented on gcloud/taskflow3/models.py
> +                sub_pipeline_node_data = {
这个是之前constants爷到孙传递时，我根据子流程节点特征搞得值传递，我换成unfold_subprocess的通用解决方法

2022-01-17 03:40 UTC, homholueng requested changes

2022-01-17 03:40 UTC, homholueng commented on pipeline_web/preview_base.py
> +class PipelineTemplateWebPreview(object):
PipelineTemplateWebPreviewer

2022-01-17 03:40 UTC, homholueng commented on gcloud/template_base/domains/template_manager.py
> +                pipeline_template_id_list.append(template.pipeline_template.template_id)
delete_pipeline_template_id_list

2022-01-17 06:36 UTC, homholueng approved these changes

2022-01-17 06:36 UTC, merged