feature: tastypie2drf一期
Tencent/bk-sops pull request #4992
Opened 2022-01-18 11:14 UTC by feifeizhao4754

2022-01-20 07:39 UTC, normal-wls requested changes

2022-01-20 07:39 UTC, normal-wls commented on gcloud/core/apis/drf/viewsets/component_model.py
> +    serializer_class = ListSerializer
ListSerializer、DetailSerializer名称需要具化一些

2022-01-20 07:39 UTC, normal-wls commented on gcloud/core/apis/drf/viewsets/label.py
> +    permission_classes = [permissions.IsAuthenticated]
这个是否没有权限校验

2022-01-20 07:39 UTC, normal-wls commented on gcloud/core/apis/drf/viewsets/package_source.py
> +    def build_filters(
这里只调了一次，为啥要抽成函数的

2022-01-21 02:53 UTC, feifeizhao4754 commented on gcloud/core/apis/drf/viewsets/label.py
> +    permission_classes = [permissions.IsAuthenticated]
没有,只有个ReadOnlyAuthorization的校验

2022-01-21 02:53 UTC, feifeizhao4754 commented on gcloud/core/apis/drf/authentication.py
> +class CsrfExemptSessionAuthentication(SessionAuthentication):
这个先去除,本地环境没获取到csrf_token

2022-01-21 03:43 UTC, feifeizhao4754 commented on gcloud/core/apis/drf/filter.py
> +class QFilterSet(VarietyFilterSet):
验证了,可以满足

2022-01-21 03:48 UTC, feifeizhao4754 commented on gcloud/core/apis/drf/viewsets/sync_task.py
> +        "list": IamPermissionInfo(IAMMeta.ADMIN_VIEW_ACTION, res=[], has_object_permission=False),
默认会转换成[],这里只是显示声明下

2022-01-21 03:50 UTC, feifeizhao4754 commented on gcloud/core/apis/drf/viewsets/base.py
> +    default_limit = 10
这里不写默认值,会拉取全部数据

2022-01-21 03:58 UTC, feifeizhao4754 commented on gcloud/core/apis/drf/viewsets/base.py
> +    if settings.RUN_MODE == "DEVELOP":
暂先去掉,上线验证

2022-01-21 06:56 UTC, feifeizhao4754 commented on gcloud/core/apis/drf/permission.py
> +        iam_action=None,
IamPermission,为声明后才会具有权限,不声明会默认拒绝
比如想启用list还不想参与权限校验,iam_action参数可以不填

2022-01-21 08:34 UTC, feifeizhao4754 commented on gcloud/core/apis/drf/permission.py
> +        :param has_object_permission: has_object_permission 启用
同意

2022-01-23 02:49 UTC, normal-wls approved these changes

2022-01-23 02:49 UTC, normal-wls commented on gcloud/core/apis/drf/permission.py
> +        to_permission="resource",
这里修改成check_hook="has_permission"/check_hook="has_object_permission"
这里可以定义两个常量

2022-01-23 02:49 UTC, normal-wls commented on gcloud/core/apis/drf/permission.py
> +        if permission_info.to_permission == permission_from:
写成 if permission_info.check_hook != check_hook: return True, 加一些注释

2022-01-23 02:49 UTC, normal-wls commented on gcloud/core/apis/drf/permission.py
> +        return self.check_permission(request, view, permission_from="resource")
check_hook=self.__name__

2022-01-23 03:18 UTC, feifeizhao4754 commented on gcloud/core/apis/drf/permission.py
> +        return self.check_permission(request, view, permission_from="resource")
不支持这类写法
需要self.has_permission.__name__这样,
这里使用常量了

2022-01-23 09:49 UTC, normal-wls approved these changes

2022-01-23 09:49 UTC, normal-wls commented on gcloud/core/apis/drf/filter.py
> +class AllLookupSupportFilterSetMetaclass(type):
这里写宽一点，支持可配置，从cls里面读取某个属性，然后进行动态配置

2022-01-23 09:49 UTC, normal-wls commented on gcloud/core/apis/drf/filter.py
> +class AllLookupSupportFilterSetMetaclass(type):
名字也需要改一下，加一下注释说明这个类的用途

2022-01-23 09:49 UTC, normal-wls commented on gcloud/core/apis/drf/filter.py
> +
fields = fields_lookups.keys() if fields == "__all__" else fields

2022-01-23 11:19 UTC, normal-wls approved these changes

2022-01-23 11:29 UTC, merged