Tastpie2drf三期改造
Tencent/bk-sops pull request #5181
Opened 2022-03-04 09:52 UTC by DomineCore

2022-03-10 04:26 UTC, normal-wls requested changes

2022-03-10 04:26 UTC, normal-wls commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +        "list": IamPermissionInfo(IAMMeta.TASK_VIEW_ACTION),
list操作鉴权重写了has_permission是否会失效

2022-03-10 08:56 UTC, normal-wls requested changes

2022-03-10 08:56 UTC, normal-wls commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +        return self.check_permission(request, view, check_hook=HAS_PERMISSION)
这里是不是直接用super().has_permission即可

2022-03-11 02:13 UTC, normal-wls approved these changes

2022-03-11 02:16 UTC, luofann approved these changes

2022-03-15 06:48 UTC, merged