批量更新子流程支持选择执行方案
Tencent/bk-sops pull request #5233
Opened 2022-03-14 05:12 UTC by wheel-w

批量更新子流程支持选择执行方案

2022-03-14 13:29 UTC, normal-wls requested changes

2022-03-14 13:29 UTC, normal-wls commented on gcloud/tasktmpl3/apis/drf/permissions.py
> +    def is_allowed_batch_view_flow(self, request, template_source, flows):
感觉流程这块的鉴权大量重复，后续会写一个单独的鉴权模块，考虑借用那个模块处理

2022-03-14 13:29 UTC, normal-wls commented on gcloud/taskflow3/apis/drf/viewsets/preview_task_tree.py
> +            if template_source == PROJECT:
这一块不需要放在try中，或者需要单独catch Doesnotexist的情况

2022-03-14 13:29 UTC, normal-wls commented on gcloud/tasktmpl3/apis/drf/viewsets/batch_form_with_schemes.py
> +        # 将项目流程和公共流程分组
直接在传参分组是不是就可以

2022-03-14 13:29 UTC, normal-wls commented on gcloud/tasktmpl3/apis/drf/viewsets/batch_form_with_schemes.py
> +        scheme_queryset = TemplateScheme.objects.filter(template__id__in=pipeline_template_ids).values(
template_id__in

2022-03-14 13:29 UTC, normal-wls commented on gcloud/tasktmpl3/apis/drf/viewsets/batch_form_with_schemes.py
> +                if index == 0:
这里的实现很奇怪，尽量不要用下标或次数来进行标识

2022-03-14 13:29 UTC, normal-wls commented on gcloud/tasktmpl3/apis/drf/viewsets/form_with_schemes.py
> +        except Exception as e:
同上修改

2022-03-15 02:33 UTC, wheel-w commented on gcloud/tasktmpl3/urls.py
> +    url(r"^api/form_with_schemes/", TemplateFormWithSchemesView.as_view()),
我关注下，这个等接口切换到form_with_schemes和batch_form_with_schemes再和前端同学确认下

2022-03-15 02:50 UTC, wheel-w commented on gcloud/tasktmpl3/apis/drf/viewsets/batch_form_with_schemes.py
> +        # 将项目流程和公共流程分组
前端在传参的时候进行分组也行，在后端分的话，前端现有逻辑修改的少

2022-03-15 02:52 UTC, wheel-w commented on gcloud/tasktmpl3/apis/drf/viewsets/batch_form_with_schemes.py
> +                if index == 0:
因为每个模板要获取两次表单数据一次当前版本的，一次最新版本的，两次逻辑只有version一个参数不一样，就用了下标标识，不过是否是当前版本使用了is_current字段，这里这样只是为了减少重复代码

2022-03-15 02:58 UTC, wheel-w commented on gcloud/tasktmpl3/apis/drf/permissions.py
> +    def is_allowed_batch_view_flow(self, request, template_source, flows):
我关注下，后续调整

2022-03-15 06:43 UTC, wheel-w commented on gcloud/tasktmpl3/apis/drf/permissions.py
> +        template_source = request.data["template_source"]
其他地方有的叫template_type，有的叫template_source
之前子流程表单渲染前端传入的是template_source，这块就不变了吧，不然相关的接口一个template_type，一个template_source

2022-03-22 04:04 UTC, normal-wls approved these changes

2022-03-22 04:04 UTC, merged