bugfix: job执行作业插件v1.1版本输出表单没有展示log_outputs字段
Tencent/bk-sops pull request #5274
Opened 2022-03-21 03:23 UTC by wheel-w

bugfix: job执行作业插件v1.1版本输出表单没有展示log_outputs字段

2022-03-24 08:29 UTC, homholueng requested changes

2022-03-24 08:29 UTC, homholueng commented on pipeline_plugins/components/collections/sites/open/job/execute_task/v1_1.py
> +        return super(JobExecuteTaskService, self).inputs_format() + [
1. 使用 python3 的方式？super()
2. 1_0 版本也需要调整

2022-03-25 03:21 UTC, wheel-w commented on pipeline_plugins/components/collections/sites/open/job/execute_task/v1_1.py
> +        return super(JobExecuteTaskService, self).inputs_format() + [
1_0 版本直接继承的
<img width="490" alt="image" src="https://user-images.githubusercontent.com/61050624/160047853-4da94c73-cbfe-4c14-821f-81f7961bb5c4.png">

2022-03-25 03:59 UTC, homholueng approved these changes

2022-03-25 04:00 UTC, merged