第三方插件data api传入bk_ticket
Tencent/bk-sops pull request #5492
Opened 2022-04-26 10:53 UTC by wheel-w

2022-04-29 03:31 UTC, homholueng requested changes

2022-04-29 03:31 UTC, homholueng commented on plugin_service/api.py
> +    bk_ticket = request.COOKIES.get("bk_ticket")
这里不能写死 bk_ticket，需要考虑 bk_token 的情况，使用的认证字段应该支持通过环境变量配置，或者根据当前环境类型自动配置

2022-05-05 02:09 UTC, homholueng requested changes

2022-05-05 02:09 UTC, homholueng commented on plugin_service/env.py
> +APIGW_USER_AUTH_KEY_NAME = os.getenv("BKAPP_APIGW_USER_AUTH_KEY_NAME", "bk_ticket")
对于外部版来说，默认的凭证应该使用 bk_token

2022-05-05 02:09 UTC, homholueng commented on plugin_service/plugin_client.py
> +    def _prepare_apigw_api_request(self, path_params: list, inject_authorization: dict = {}):
```
inject_authorization: dict = None
```

2022-05-05 02:09 UTC, homholueng commented on plugin_service/plugin_client.py
> +    def dispatch_plugin_api_request(self, request_params, inject_headers=None, inject_authorization={}):
```
inject_authorization: dict = None
```

2022-05-05 03:15 UTC, homholueng approved these changes

2022-05-05 03:23 UTC, normal-wls approved these changes

2022-05-05 03:23 UTC, merged