节点日志新增支持远程数据源拉取方式
Tencent/bk-sops pull request #5535
Opened 2022-05-06 05:15 UTC by normal-wls

2022-05-09 02:10 UTC, homholueng requested changes

2022-05-09 02:10 UTC, homholueng commented on gcloud/taskflow3/apis/drf/viewsets/engine_v2_node_log.py
> +        if settings.ENABLE_NODE_LOG_PULL:
使用 NodeLogDataSource 抽象工厂来返回特定的实现，不要使用 if else

2022-05-09 02:10 UTC, homholueng commented on config/default.py
> +ENABLE_NODE_LOG_PULL = env.ENABLE_NODE_LOG_PULL
采用数据源类型，数据源类型所需要的参数的模式来配置：

- NODE_LOG_DATA_SOURCE
- NODE_LOG_DATA_SOURCE_CONFIG

2022-05-12 02:54 UTC, homholueng requested changes

2022-05-12 02:54 UTC, homholueng commented on gcloud/taskflow3/domains/node_log.py
> +    def fetch_node_logs(self, request, node_id, version_id, *args, **kwargs):
request 参数？

2022-05-12 02:54 UTC, homholueng commented on gcloud/taskflow3/domains/node_log.py
> +        return {"result": True, "data": {"logs": logs, "page_info": {}}, "message": ""}
这里 page_info 返回空字典是否会影响前端的处理逻辑？

2022-05-12 02:55 UTC, normal-wls commented on gcloud/taskflow3/domains/node_log.py
> +        return {"result": True, "data": {"logs": logs, "page_info": {}}, "message": ""}
空字典可以用来判断不分页的情况

2022-05-16 02:02 UTC, homholueng approved these changes

2022-05-16 02:02 UTC, merged