IPV6 JOB+CC+节点管理改造
Tencent/bk-sops pull request #6027
Opened 2022-09-13 03:02 UTC by hanshuaikang

目前未完成
- job 上传文件/跨业务(需要job提供接口支持)
- 节点管理 新建任务 插件

2022-09-19 09:22 UTC, normal-wls requested changes

2022-09-19 09:22 UTC, normal-wls commented on pipeline_plugins/components/utils/sites/open/utils.py
> +    return []
return set()

2022-09-19 09:39 UTC, hanshuaikang commented on pipeline_plugins/components/collections/sites/open/job/local_content_upload/v1_0.py
> +                return False
日志的话，get_target_server 里面会打

2022-09-19 09:43 UTC, hanshuaikang commented on pipeline_plugins/components/collections/sites/open/job/ipv6_base.py
> +        return True, {"host_id_list": [int(host["bk_host_id"]) for host in host_result["data"]]}
插件识别了这个协议，改动的话影响比较大

2022-09-19 09:48 UTC, hanshuaikang commented on gcloud/utils/cmdb.py
> +            "rules": [{"field": "bk_host_innerip", "operator": "in", "value": ip_list}],
不会有问题，上层不可能会传none进来，bk_cloud_id我去掉吧

2022-09-19 10:01 UTC, hanshuaikang commented on pipeline_plugins/components/collections/sites/open/cc/ipv6_utils.py
> +        if plat_ip in ipv4_list_with_cloud_id:
只判断是否存在的话应该不用去重吧

2022-09-19 10:05 UTC, hanshuaikang commented on pipeline_plugins/components/collections/sites/open/nodeman/ip_v6_base.py
> +        def build_ip_str():
这个暂时只会在这里用到，这个地方比较特殊

2022-09-20 08:55 UTC, normal-wls approved these changes

2022-09-20 08:55 UTC, normal-wls commented on config/default.py
> -OPEN_IP_V6 = env.OPEN_IP_V6
IPV6

2022-09-20 09:22 UTC, merged