后台管理—计划任务接口开发
Tencent/bk-sops pull request #6192
Opened 2022-10-19 09:30 UTC by guanjianqiang0408

接口说明：
GET /api/v4/clocked_task/list_all/
Params
        limit 
        offset

Headers
        Cookie
        X-CSRFToken

2022-10-19 11:29 UTC, normal-wls requested changes

2022-10-19 11:29 UTC, normal-wls commented on gcloud/clocked_task/viewset.py
> +        if Project.objects.filter(pk=request.query_params.get("project_id")).exists():
这里不需要做这个判断

2022-10-19 11:29 UTC, normal-wls commented on gcloud/clocked_task/viewset.py
> +    def construct_response_data(self, request, queryset):
一般不建议把Response作为工具函数的返回，因为调用方不好在下游做进一步处理，尽量返回dict，在view里面包成Response

2022-10-19 11:29 UTC, normal-wls commented on gcloud/clocked_task/viewset.py
> +    def list_all(self, request):
需要补充单元测试

2022-10-20 02:53 UTC, guanjianqiang0408 commented on gcloud/clocked_task/viewset.py
> +        if Project.objects.filter(pk=request.query_params.get("project_id")).exists():
去掉了这个接口，统一使用list

2022-10-20 02:53 UTC, guanjianqiang0408 commented on gcloud/clocked_task/viewset.py
> +    def construct_response_data(self, request, queryset):
问题已整改

2022-10-20 02:53 UTC, guanjianqiang0408 commented on gcloud/clocked_task/viewset.py
> +    def list_all(self, request):
使用原有list接口，没有新增接口

2022-10-21 02:22 UTC, normal-wls requested changes

2022-10-21 02:22 UTC, normal-wls commented on gcloud/clocked_task/permissions.py
> -from .serializer import ClockedTaskListPermissionSerializer
看看这个Serializer是否有其他地方用到，没有的话把代码去掉

2022-10-21 02:22 UTC, normal-wls commented on gcloud/clocked_task/permissions.py
> +            project_id = request.query_params.get("project_id")
确认下这里不转成int是否有问题

2022-10-21 06:21 UTC, normal-wls approved these changes

2022-10-21 06:21 UTC, merged