任务操作记录增加参数修改明细
Tencent/bk-sops pull request #6304
Opened 2022-11-14 09:56 UTC by guanjianqiang0408

任务修改参数接口
Api 路由及请求方式： taskflow/api/update_task_constants/<task_id>/ POST
请求参数:
{
"instance_id": "7538",
"constants": {
"${description}": "20",
"${job_list}": "",
"${ip_list}": ""
},
"modified_constant_keys": ["${description}"]
}
参数说明： 如果指定modified_constant_keys，则记录modified_constant_keys对应属性内容; 如果没有指定，则记录所有任务参数内容
响应内容不变

任务操作记录接口：
API 路由及请求方式: api/v3/operate_record_task/?project_id=<project_id>&instance_id=<instance_id> GET
响应内容多增加了extra_info属性，前端通过该属性渲染参数内容
extra_info属性示例:
"extra_info": {
"${description}": {
"name": "描述",
"value": "20"
}
}

2022-11-16 08:51 UTC, normal-wls requested changes

2022-11-16 08:51 UTC, normal-wls commented on gcloud/utils/handlers.py
> +    获取pipeline_tree中constant参数值
这一块的注释跟这个函数的作用关系不大，描述的是外层如何进行数据准备

2022-11-16 08:51 UTC, normal-wls commented on gcloud/utils/handlers.py
> +def get_constants(constants, keys):
这个函数最好放在record的相关模块下，这里的逻辑并不是很通用。函数名最好也具体一些

2022-11-16 08:51 UTC, normal-wls commented on gcloud/contrib/operate_record/core.py
> +        constants = self.operate_result["data"]["pipeline_tree"]["constants"]
这里需要考虑是否会有keyError的情况

2022-11-17 04:04 UTC, guanjianqiang0408 commented on gcloud/contrib/operate_record/apis/drf/serilaziers/operate_record.py
> +            if obj.extra_info and not isinstance(obj.extra_info, dict)
已修改

2022-11-17 04:05 UTC, guanjianqiang0408 commented on gcloud/utils/handlers.py
> +    获取pipeline_tree中constant参数值
该函数已经转移到gcloud.contrib.operate_record.utils文件中，并修改函数名为extract_extra_info

2022-11-17 04:05 UTC, guanjianqiang0408 commented on gcloud/utils/handlers.py
> +def get_constants(constants, keys):
已处理

2022-11-17 04:06 UTC, guanjianqiang0408 commented on gcloud/contrib/operate_record/core.py
> +        constants = self.operate_result["data"]["pipeline_tree"]["constants"]
已处理，如果constants值为空，默认为空字符串

2022-11-17 04:06 UTC, guanjianqiang0408 commented on gcloud/taskflow3/apis/drf/viewsets/update_task_constants.py
> +            constants = task.pipeline_instance.execution_data["constants"]
已处理，如果constants值为空，默认为空字符串

2022-11-17 04:06 UTC, guanjianqiang0408 commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +        constants = pipeline_instance.execution_data["constants"]
已处理，如果constants值为空，默认为空字符串

2022-11-17 07:11 UTC, normal-wls requested changes

2022-11-17 07:11 UTC, normal-wls commented on gcloud/contrib/operate_record/utils.py
> +import json
加上文件顶部的开源协议注释

2022-11-17 07:11 UTC, normal-wls commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +        if not constants:
extra_info = xxx if constants else ""

2022-11-17 07:11 UTC, normal-wls commented on gcloud/contrib/operate_record/core.py
> +        constants = self.operate_result["data"]["pipeline_tree"].get("constants")
operate_result的类型是否为dict、dict中包含什么key都不是确定的，这样取仍然可能有问题

2022-11-17 07:11 UTC, normal-wls commented on gcloud/contrib/operate_record/core.py
> +        if not constants:
extra_info = xxx if constants else ""

2022-11-17 07:11 UTC, normal-wls commented on gcloud/taskflow3/apis/drf/viewsets/update_task_constants.py
> +            if not constants:
这里的这些判断，是否直接放在extract_extra_info函数里面会更好，不然每个外层调用方都要判断一次

2022-11-17 09:36 UTC, guanjianqiang0408 commented on gcloud/contrib/operate_record/utils.py
> +import json
已添加

2022-11-17 09:37 UTC, guanjianqiang0408 commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +        if not constants:
处理逻辑统一放到extract_extra_info函数中处理

2022-11-17 09:38 UTC, guanjianqiang0408 commented on gcloud/contrib/operate_record/core.py
> +        if not constants:
处理逻辑统一放到extract_extra_info函数中处理

2022-11-17 09:38 UTC, guanjianqiang0408 commented on gcloud/taskflow3/apis/drf/viewsets/update_task_constants.py
> +            if not constants:
处理逻辑统一放到extract_extra_info函数中处理

2022-11-17 11:26 UTC, normal-wls requested changes

2022-11-17 11:26 UTC, normal-wls commented on gcloud/contrib/operate_record/utils.py
> +Copyright (C) 2017-2020 THL A29 Limited, a Tencent company. All rights reserved.
2020可以去掉

2022-11-17 11:26 UTC, normal-wls commented on gcloud/contrib/operate_record/core.py
> +        constants = instance_obj.pipeline_instance.execution_data.get("constant")
需要确定这里的instance_obj是否肯定为TaskflowInstance，如果不是，则需要提前判断

2022-11-18 01:27 UTC, guanjianqiang0408 commented on gcloud/contrib/operate_record/utils.py
> +Copyright (C) 2017-2020 THL A29 Limited, a Tencent company. All rights reserved.
已删除

2022-11-18 01:29 UTC, guanjianqiang0408 commented on gcloud/contrib/operate_record/core.py
> +        constants = instance_obj.pipeline_instance.execution_data.get("constant")
增加了instance_obj对象类型的校验逻辑。 初始化记录数据没有extra_info属性，如果instance_obj类型为TaskFlowInstnace条件满足，向原初始化记录数据中添加extra_info属性和内容

2022-11-18 02:31 UTC, normal-wls approved these changes

2022-11-18 02:32 UTC, merged