后台报错内容优化
Tencent/bk-sops pull request #6324
Opened 2022-11-16 07:37 UTC by guanjianqiang0408

2022-11-17 07:02 UTC, normal-wls requested changes

2022-11-17 12:48 UTC, normal-wls requested changes

2022-11-17 12:48 UTC, normal-wls commented on gcloud/taskflow3/apis/django/v4/node_callback.py
> +        message = __(f"节点回调失败:: 无效的请求, 请重试. 如持续失败可联系管理员处理. {traceback.format_exc()} | node_callback")
_

2022-11-18 02:15 UTC, guanjianqiang0408 commented on gcloud/taskflow3/apis/django/api.py
> +        frequence_result = get_task_operation_frequence(project_id, action)
已修改frequence_result, frequence_data = get_task_operation_frequence(project_id, action)

2022-11-18 02:15 UTC, guanjianqiang0408 commented on gcloud/taskflow3/apis/django/api.py
> +        if frequence_result[0]:
已修改

2022-11-18 02:15 UTC, guanjianqiang0408 commented on gcloud/taskflow3/apis/django/api.py
> +            allowed_times, scope_seconds = frequence_result[1][0], frequence_result[1][1]
已修改

2022-11-18 02:15 UTC, guanjianqiang0408 commented on gcloud/taskflow3/celery/tasks.py
> +        message = _(f"超时策略激活失败: 节点[ID: {node_id}], 版本[{version}], 任务[ID: {task_id}] 现已通过 "
已处理

2022-11-18 02:15 UTC, guanjianqiang0408 commented on gcloud/taskflow3/apis/django/v4/node_callback.py
> +        message = __(f"节点回调失败:: 无效的请求, 请重试. 如持续失败可联系管理员处理. {traceback.format_exc()} | node_callback")
已处理

2022-11-18 02:15 UTC, guanjianqiang0408 commented on gcloud/taskflow3/apis/django/api.py
> +        message = _(f"节点回调失败:: 无效的请求, 请重试. 如持续失败可联系管理员处理. {traceback.format_exc()} | api node_callback")
已处理

2022-11-18 02:15 UTC, guanjianqiang0408 commented on gcloud/taskflow3/apis/django/api.py
> +        message = _(f"节点状态请求失败: 任务[ID: {task.id}]中未找到节点[ID: {node_id}]. 请重试" f" 如持续失败可联系管理员处理 | get_node_log")
已处理

2022-11-18 02:16 UTC, guanjianqiang0408 commented on gcloud/contrib/function/api.py
> +            message = _(f"任务转交失败: 仅[{claimant}]才可转交任务, 请检查是否已认领该任务 | transferView post")
已处理

2022-11-18 02:16 UTC, guanjianqiang0408 commented on gcloud/taskflow3/models.py
> +            message = _(f"节点状态请求失败: 任务[ID: {self.id}]中未找到节点[ID: {node_id}]. 请重试" f" 如持续失败可联系管理员处理 | get_node_detail")
已处理

2022-11-18 02:16 UTC, guanjianqiang0408 commented on gcloud/taskflow3/models.py
> +            message = _(f"节点状态请求失败: 任务[ID: {self.id}]中未找到节点[ID: {node_id}]. 请重试" f" 如持续失败可联系管理员处理 | get_node_data")
已处理

2022-11-18 02:16 UTC, guanjianqiang0408 commented on gcloud/taskflow3/models.py
> +            message = _(f"节点操作失败: 节点[ID: {node_id}], 任务[ID: {self.id}]操作失败: {e}, 请重试. " f"如持续失败可联系管理员处理 | nodes_action")
已处理

2022-11-18 07:11 UTC, normal-wls requested changes

2022-11-18 07:11 UTC, normal-wls commented on gcloud/template_base/domains/template_manager.py
> +            message = _(f"保存流程失败: 创建模板失败, 请检查流程. 创建参数[{template_kwargs}], 失败原因: [{e}] | create")
verbose_message中的traceback.format_exc()保留，不要因为提示的修改有信息的损失

2022-11-18 07:11 UTC, normal-wls commented on gcloud/template_base/domains/template_manager.py
> +                message = _(f"保存流程失败: 流程树合法性校验失败, 请检查流程. 失败原因: {e} | update_pipeline")
verbose_message中的traceback.format_exc()保留，不要因为提示的修改有信息的损失

2022-11-18 07:11 UTC, normal-wls commented on gcloud/template_base/domains/template_manager.py
> +                message = _(f"更新流程失败: 更新Pipeline失败, 请检查流程. 更新参数: [{update_kwargs}], 失败原因: [{e}] | update_pipeline")
verbose_message中的traceback.format_exc()保留，不要因为提示的修改有信息的损失

2022-11-18 07:11 UTC, normal-wls commented on gcloud/template_base/domains/template_manager.py
> +                "流程删除失败: 流程已被其他小程序引用[{}], 暂不可删除, 请处理后重试 | can_delete".format(
小程序->轻应用

2022-11-18 07:11 UTC, normal-wls commented on gcloud/template_base/domains/template_manager.py
> +                "流程删除失败: 流程已被其他定时任务引用[{}], 暂不可删除, 请处理后重试 | can_delete".format(
计划任务

2022-11-18 07:11 UTC, normal-wls commented on pipeline_plugins/base/query/cmdb.py
> +        message = _(f"保存失败: 调用保存接口参数校验失败. 错误信息: {e} | cc_search_module")
保存接口？
这里用原来的描述即可

2022-11-18 07:11 UTC, normal-wls commented on pipeline_plugins/components/query/sites/open/job.py
> +            f"请求执行方案失败: 请求[作业平台]的执行方案[ID: {biz_cc_id}]返回失败: {job_result['message']}. "
语义有问题，biz_cc_id不是执行方案ID

2022-11-18 07:11 UTC, normal-wls commented on pipeline_plugins/components/query/sites/open/job.py
> +        message = _(f"请求执行方案失败: 请求[作业平台]的执行方案[ID: {job_result}]返回为空. 请重试, 如持续失败请联系管理员处理 | job_get_job_task_detail")
job_result不是执行方案ID

2022-11-18 07:11 UTC, normal-wls commented on pipeline_plugins/components/query/sites/open/job.py
> +            f"执行历史请求失败: 请求[作业平台ID: {biz_cc_id}]. 异常消息: {job_result['message']} | job_get_instance_detail"
biz_cc_id是业务id，如果不知道怎么改，可以尽可能用原来的提示内容

2022-11-18 07:11 UTC, normal-wls commented on pipeline_plugins/components/query/sites/open/job.py
> +        message = _(f"请求执行方案失败: 请求[作业平台]的执行方案[ID: {jobv3_result}]返回为空. 请重试, 如持续失败请联系管理员处理 | jobv3_get_job_plan_detail")
result不是id

2022-11-18 07:11 UTC, normal-wls commented on pipeline_plugins/components/query/sites/open/job.py
> +            f"请求执行方案失败: 请求[作业平台]的执行方案[ID: {biz_cc_id}]返回失败: {job_result['message']}. "
cc_id不是执行方案id

2022-11-18 07:21 UTC, guanjianqiang0408 commented on pipeline_plugins/components/query/sites/open/job.py
> +            f"请求执行方案失败: 请求[作业平台]的执行方案[ID: {biz_cc_id}]返回失败: {job_result['message']}. "
已经根据原来报错内容进行内容整改

2022-11-18 07:23 UTC, guanjianqiang0408 commented on pipeline_plugins/components/query/sites/open/job.py
> +        message = _(f"请求执行方案失败: 请求[作业平台]的执行方案[ID: {jobv3_result}]返回为空. 请重试, 如持续失败请联系管理员处理 | jobv3_get_job_plan_detail")
已根据原报错内容整改

2022-11-18 07:23 UTC, guanjianqiang0408 commented on pipeline_plugins/components/query/sites/open/job.py
> +            f"执行历史请求失败: 请求[作业平台ID: {biz_cc_id}]. 异常消息: {job_result['message']} | job_get_instance_detail"
已根据原内容整改

2022-11-18 07:24 UTC, guanjianqiang0408 commented on pipeline_plugins/components/query/sites/open/job.py
> +        message = _(f"请求执行方案失败: 请求[作业平台]的执行方案[ID: {job_result}]返回为空. 请重试, 如持续失败请联系管理员处理 | job_get_job_task_detail")
已整改

2022-11-18 07:24 UTC, guanjianqiang0408 commented on pipeline_plugins/components/query/sites/open/job.py
> +            f"请求执行方案失败: 请求[作业平台]的执行方案[ID: {biz_cc_id}]返回失败: {job_result['message']}. "
已整改

2022-11-18 07:25 UTC, guanjianqiang0408 commented on pipeline_plugins/base/query/cmdb.py
> +        message = _(f"保存失败: 调用保存接口参数校验失败. 错误信息: {e} | cc_search_module")
已整改

2022-11-18 07:25 UTC, guanjianqiang0408 commented on gcloud/template_base/domains/template_manager.py
> +                "流程删除失败: 流程已被其他定时任务引用[{}], 暂不可删除, 请处理后重试 | can_delete".format(
已整改

2022-11-18 07:29 UTC, guanjianqiang0408 commented on gcloud/template_base/domains/template_manager.py
> +                message = _(f"更新流程失败: 更新Pipeline失败, 请检查流程. 更新参数: [{update_kwargs}], 失败原因: [{e}] | update_pipeline")
已整改

2022-11-18 07:29 UTC, guanjianqiang0408 commented on gcloud/template_base/domains/template_manager.py
> +                message = _(f"保存流程失败: 流程树合法性校验失败, 请检查流程. 失败原因: {e} | update_pipeline")
已整改

2022-11-18 07:30 UTC, guanjianqiang0408 commented on gcloud/template_base/domains/template_manager.py
> +            message = _(f"保存流程失败: 创建模板失败, 请检查流程. 创建参数[{template_kwargs}], 失败原因: [{e}] | create")
已整改

2022-11-18 07:30 UTC, guanjianqiang0408 commented on gcloud/template_base/domains/template_manager.py
> +            message = _(f"保存流程失败: 创建Pipeline流程失败, 请检查流程. 创建参数[{create_template_kwargs}], 失败原因: [{e}] | create_pipeline")
已整改

2022-11-18 07:30 UTC, guanjianqiang0408 commented on gcloud/template_base/domains/template_manager.py
> +            message = _(f"保存流程失败: 流程树合法性校验失败, 请检查流程. 失败原因: {e} | create_pipeline")
已整改

2022-11-18 07:32 UTC, guanjianqiang0408 commented on pipeline_plugins/components/collections/sites/open/cc/batch_transfer_host_module/v1_1.py
> +                    f"主机所属业务模块更新失败: 主机属性={attr}, 更新属性: {cc_kwargs}, 错误信息: {update_result['message']}"
整改为kwargs： {cc_kwargs}

2022-11-18 07:32 UTC, guanjianqiang0408 commented on pipeline_plugins/components/collections/sites/open/cc/batch_transfer_host_module/v1_0.py
> +                    f"主机所属业务模块更新失败: 主机属性={attr}, 更新属性: {cc_kwargs}, 错误信息: {update_result['message']}"
整改为kwargs： {cc_kwargs}

2022-11-18 07:34 UTC, guanjianqiang0408 commented on gcloud/utils/throttle.py
> +    allowed_times, scope_seconds = function_result[1][0], function_result[1][1]
已处理

2022-11-18 07:34 UTC, guanjianqiang0408 commented on gcloud/utils/throttle.py
> +    function_result = get_task_operation_frequence(project_id, operation)
已处理

2022-11-18 07:38 UTC, guanjianqiang0408 commented on gcloud/taskflow3/apis/django/api.py
> +        if frequence_result:
已整改

2022-11-18 07:40 UTC, guanjianqiang0408 commented on pipeline_plugins/components/query/sites/open/file_upload.py
> +        message = _(f"文件上传失败: 请重试，如持续失败可联系管理员处理. 业务[ID: {bk_biz_id}], 名称: {name} | get_repo_temporary_upload_url")
已整改

2022-11-18 08:43 UTC, normal-wls requested changes

2022-11-18 08:43 UTC, normal-wls commented on pipeline_plugins/base/query/cmdb.py
> +        message = _(f"保存失败: 请求参数格斯校验失败. 错误信息: {e} | cc_search_module")
格式

2022-11-18 08:43 UTC, normal-wls commented on pipeline_plugins/components/query/sites/open/job.py
> +        message = _(f"请求执行方案失败: 请求作业平台执行方案详情返回数据为空: {job_result}]返回为空. 请重试, 如持续失败请联系管理员处理 | job_get_job_task_detail")
多了]

2022-11-18 08:48 UTC, guanjianqiang0408 commented on pipeline_plugins/components/query/sites/open/job.py
> +        message = _(f"请求执行方案失败: 请求作业平台执行方案详情返回数据为空: {job_result}]返回为空. 请重试, 如持续失败请联系管理员处理 | job_get_job_task_detail")
已整改

2022-11-18 08:48 UTC, guanjianqiang0408 commented on pipeline_plugins/base/query/cmdb.py
> +        message = _(f"保存失败: 请求参数格斯校验失败. 错误信息: {e} | cc_search_module")
已整改

2022-11-18 08:56 UTC, normal-wls approved these changes

2022-11-21 01:48 UTC, merged